// Generated by `make apigen` from the Go types in backend/internal.
// Do not edit by hand: change the Go structs and regenerate.

export type Asset = {
  carousel_id?: string;
  created_at: string;
  file_size: number;
  height: number;
  id: string;
  metadata?: Record<string, unknown>;
  mime_type: string;
  project_id?: string;
  source: string;
  source_id?: string;
  url?: string;
  user_id: string;
  width: number;
};

export type AuthConfigResponse = {
  dev_login_enabled: boolean;
  google_enabled: boolean;
};

export type AuthUser = {
  avatar_url: string;
  created_at: string;
  email: string;
  id: string;
  name: string;
  provider: string;
};

export type Carousel = {
  canvas_height: number;
  canvas_ratio: string;
  canvas_width: number;
  created_at: string;
  design_version: number;
  formula_id: string;
  id: string;
  input?: Record<string, unknown>;
  platform: string;
  project_id: string;
  schema_version: number;
  status: string;
  thumbnail_url?: string;
  title: string;
  updated_at: string;
};

export type CarouselCaption = {
  caption: string;
  edited: boolean;
  generated_at?: string | null;
  hashtags: string[];
  updated_at: string;
};

export type CarouselDesignView = {
  design: Design;
  version: number;
};

export type CarouselResponse = {
  carousel: Carousel;
  job?: Job;
};

export type CarouselsResponse = {
  carousels: Carousel[];
};

export type ContentDocument = {
  formula_id: string;
  formula_reason: string;
  schema_version: string;
  slides: Record<string, unknown>[];
  title: string;
};

export type CreateProjectRequest = {
  language: string;
  niche: string;
};

export type Design = {
  canvas: DesignCanvas;
  palette: DesignPalette;
  slides: DesignSlide[];
  version: string;
};

export type DesignCanvas = {
  height: number;
  ratio: string;
  reserved_bottom?: number;
  reserved_top?: number;
  safe_area: DesignSafeArea;
  width: number;
};

export type DesignElement = {
  asset_id?: string;
  content?: string;
  fill?: string;
  fit?: string;
  height: number;
  id: string;
  locked?: boolean;
  opacity: number;
  overlay?: DesignOverlay;
  radius?: number;
  role?: string;
  shape?: string;
  style?: DesignStyle;
  type: string;
  url?: string;
  width: number;
  x: number;
  y: number;
  z: number;
};

export type DesignOverlay = {
  color: string;
  opacity: number;
};

export type DesignPalette = {
  accent: string;
  background: string;
  primary: string;
  secondary: string;
  text: string;
};

export type DesignPreset = {
  height: number;
  label: string;
  ratio: string;
  width: number;
};

export type DesignSafeArea = {
  height: number;
  width: number;
  x: number;
  y: number;
};

export type DesignSlide = {
  background: string;
  elements: DesignElement[];
  id: string;
  image_intent?: string;
  image_query?: string;
  index: number;
  role: string;
  template?: string;
};

export type DesignStyle = {
  color: string;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  lineHeight: number;
  textAlign: string;
};

export type DevLoginRequest = {
  email: string;
  name?: string;
};

export type ErrorResponse = {
  error: Record<string, unknown>;
};

export type ExportJob = {
  carousel_id: string;
  completed_at?: string | null;
  created_at: string;
  download_url?: string;
  error?: string;
  format: string;
  id: string;
  progress: number;
  status: string;
};

export type GenerateCarouselRequest = {
  inputs: Record<string, unknown>;
  ratio: string;
};

export type GenerateCarouselResponse = {
  carousel: Carousel;
  carousel_id: string;
  job_id: string;
  status: string;
};

export type ImageCandidatesResponse = {
  candidates: ImagePublicCandidate[];
  page?: number;
  query: string;
};

export type ImagePublicCandidate = {
  color?: string;
  description?: string;
  height: number;
  id: string;
  photographer_name?: string;
  photographer_url?: string;
  preview_url: string;
  provider: string;
  source_url?: string;
  thumb_url: string;
  width: number;
};

export type Job = {
  attempt: number;
  carousel_id: string;
  completed_at?: string | null;
  created_at: string;
  current_step: string;
  error_code?: string;
  error_message?: string;
  id: string;
  last_completed_step: string;
  progress: number;
  project_id: string;
  status: string;
  type: string;
  user_id: string;
};

export type JobResponse = {
  carousel_id: string;
  current_step: string;
  error_message?: string;
  id: string;
  progress: number;
  status: string;
  steps: Record<string, unknown>[];
};

export type Language = {
  code: string;
  english_name: string;
  native_name: string;
};

export type Project = {
  brand: ProjectBrand;
  carousel_count: number;
  context?: Record<string, unknown>;
  context_version: number;
  created_at: string;
  description: string;
  id: string;
  language: string;
  name: string;
  niche: string;
  status: string;
  updated_at: string;
  user_id: string;
};

export type ProjectAudience = {
  demographics: string;
  description: string;
  pain_points: string[];
};

export type ProjectBrand = {
  accent_color?: string;
  display: ProjectBrandDisplay;
  font_family?: string;
  handle?: string;
  logo_asset_id?: string;
  logo_url?: string;
  primary_color?: string;
  secondary_color?: string;
  website?: string;
};

export type ProjectBrandDisplay = {
  handle: ProjectPlacement;
  logo: ProjectPlacement;
  website: ProjectPlacement;
};

export type ProjectCTA = {
  id: string;
  label: string;
};

export type ProjectContext = {
  audience: ProjectAudience;
  content_pillars: ProjectPillar[];
  cta_options: ProjectCTA[];
  preferred_angles: string[];
  schema_version: string;
  suggested_topics: string[];
  tone: string[];
  writing_style: string;
};

export type ProjectPillar = {
  description: string;
  id: string;
  name: string;
};

export type ProjectPlacement = {
  position: string;
  scope: string;
};

export type ProjectSource = {
  domain: string;
  source_type: string;
  title: string;
  url: string;
};

export type ProjectsResponse = {
  projects: Project[];
};

export type RegistryFont = {
  css_stack: string;
  family: string;
  id: string;
  vietnamese: boolean;
  weights: number[];
};

export type RegistryFormula = {
  description: string;
  id: string;
  name: string;
  recommended_for: string;
  structure: string[];
};

export type RegistryResponse = {
  fonts: RegistryFont[];
  formulas: RegistryFormula[];
  languages: Language[];
  presets: DesignPreset[];
};

export type SaveDesignRequest = {
  design: Design;
  version: number;
};

export type SchemaForm = {
  properties: SchemaProperty[];
  version: number;
};

export type SchemaProperty = {
  component: string;
  default?: unknown;
  description?: string;
  enum?: string[];
  enum_labels?: Record<string, string>;
  help?: string;
  items?: string;
  max_length?: number | null;
  maximum?: number | null;
  minimum?: number | null;
  name: string;
  placeholder?: string;
  required: boolean;
  title: string;
  type: string;
};

export type SchemaResponse = {
  form: SchemaForm;
  version: number;
};

export type SearchImagesRequest = {
  page?: number;
  query?: string;
};

export type SelectImageRequest = {
  candidate_id: string;
  version: number;
};

export type SelectImageResponse = {
  asset: Asset;
  version: number;
};

export type SourcesResponse = {
  sources: ProjectSource[];
};

export type UpdateCaptionRequest = {
  caption: string;
  hashtags: string[];
};

export type UpdateCarouselRequest = {
  status?: string | null;
  title?: string | null;
};

export type UpdateProjectRequest = {
  brand?: ProjectBrand;
  context?: ProjectContext;
  description?: string | null;
  language?: string | null;
  name?: string | null;
  niche?: string | null;
};

