package apispec

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// emitDart writes null-safe Dart models plus a typed API client. Hand-writing
// these was the alternative; generating them means a field added in Go cannot
// be forgotten in the app.
func emitDart(reg *Registry, ops []Operation) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Generated by `make apigen` from the Go types in backend/internal.\n")
	b.WriteString("// Do not edit by hand: change the Go structs and regenerate.\n\n")
	b.WriteString("// ignore_for_file: unnecessary_this, prefer_final_locals\n\n")
	b.WriteString("import 'dart:convert';\n\nimport 'package:http/http.dart' as http;\n\n")

	b.WriteString(`/// Thrown for any non-2xx response. The backend sends a stable `)
	b.WriteString("`code`\n/// plus a human message; the UI localises by code and falls back to the message.\n")
	b.WriteString(`class ApiException implements Exception {
  ApiException(this.statusCode, this.code, this.message);

  final int statusCode;
  final String code;
  final String message;

  @override
  String toString() => 'ApiException($statusCode, $code): $message';
}

`)

	for _, name := range reg.Names() {
		writeDartClass(&b, name, reg.Schemas[name])
	}

	writeDartClient(&b, reg, ops)
	return b.Bytes(), nil
}

func writeDartClass(b *bytes.Buffer, name string, s *Schema) {
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	var fields []string
	for f := range s.Properties {
		fields = append(fields, f)
	}
	sort.Strings(fields)

	fmt.Fprintf(b, "class %s {\n", name)

	// Constructor
	fmt.Fprintf(b, "  %s({\n", name)
	for _, f := range fields {
		dartName := dartField(f)
		if required[f] && !isNullable(s.Properties[f]) {
			fmt.Fprintf(b, "    required this.%s,\n", dartName)
		} else {
			fmt.Fprintf(b, "    this.%s,\n", dartName)
		}
	}
	b.WriteString("  });\n\n")

	// fromJson
	fmt.Fprintf(b, "  factory %s.fromJson(Map<String, dynamic> json) => %s(\n", name, name)
	for _, f := range fields {
		fmt.Fprintf(b, "        %s: %s,\n", dartField(f), dartDecode(s.Properties[f], fmt.Sprintf("json['%s']", f), required[f]))
	}
	b.WriteString("      );\n\n")

	// fields
	for _, f := range fields {
		t := dartType(s.Properties[f])
		if (!required[f] || isNullable(s.Properties[f])) && t != "dynamic" {
			t += "?"
		}
		fmt.Fprintf(b, "  final %s %s;\n", t, dartField(f))
	}

	// copyWith — the models are immutable, and the editor needs to produce a
	// changed element without reaching for a JSON round-trip.
	fmt.Fprintf(b, "\n  %s copyWith({\n", name)
	for _, f := range fields {
		t := dartType(s.Properties[f])
		if t != "dynamic" {
			t += "?"
		}
		fmt.Fprintf(b, "    %s %s,\n", t, dartField(f))
	}
	b.WriteString("  }) =>\n")
	fmt.Fprintf(b, "      %s(\n", name)
	for _, f := range fields {
		d := dartField(f)
		fmt.Fprintf(b, "        %s: %s ?? this.%s,\n", d, d, d)
	}
	b.WriteString("      );\n")

	// toJson
	b.WriteString("\n  Map<String, dynamic> toJson() => {\n")
	for _, f := range fields {
		nullable := !required[f] || isNullable(s.Properties[f])
		fmt.Fprintf(b, "        '%s': %s,\n", f, dartEncode(s.Properties[f], dartField(f), nullable))
	}
	b.WriteString("      };\n")
	b.WriteString("}\n\n")
}

func isNullable(s *Schema) bool { return s != nil && s.Nullable }

func dartType(s *Schema) string {
	if s == nil {
		return "dynamic"
	}
	if s.Ref != "" {
		return strings.TrimPrefix(s.Ref, "#/components/schemas/")
	}
	switch s.Type {
	case "string":
		if s.Format == "date-time" {
			return "DateTime"
		}
		return "String"
	case "integer":
		return "int"
	case "number":
		return "double"
	case "boolean":
		return "bool"
	case "array":
		return "List<" + dartType(s.Items) + ">"
	case "object":
		if s.AdditionalProperties != nil {
			return "Map<String, " + dartType(s.AdditionalProperties) + ">"
		}
		return "Map<String, dynamic>"
	}
	return "dynamic"
}

// dartDecode builds the expression that reads one field out of a JSON map.
func dartDecode(s *Schema, expr string, required bool) string {
	if s == nil {
		return expr
	}
	if s.Ref != "" {
		name := strings.TrimPrefix(s.Ref, "#/components/schemas/")
		if required && !s.Nullable {
			return fmt.Sprintf("%s.fromJson(%s as Map<String, dynamic>)", name, expr)
		}
		return fmt.Sprintf("%s == null ? null : %s.fromJson(%s as Map<String, dynamic>)", expr, name, expr)
	}
	switch s.Type {
	case "string":
		if s.Format == "date-time" {
			if required && !s.Nullable {
				return fmt.Sprintf("DateTime.parse(%s as String)", expr)
			}
			return fmt.Sprintf("%s == null ? null : DateTime.tryParse(%s as String)", expr, expr)
		}
		if required && !s.Nullable {
			return fmt.Sprintf("(%s as String?) ?? ''", expr)
		}
		return fmt.Sprintf("%s as String?", expr)
	case "integer":
		if required && !s.Nullable {
			return fmt.Sprintf("(%s as num?)?.toInt() ?? 0", expr)
		}
		return fmt.Sprintf("(%s as num?)?.toInt()", expr)
	case "number":
		if required && !s.Nullable {
			return fmt.Sprintf("(%s as num?)?.toDouble() ?? 0", expr)
		}
		return fmt.Sprintf("(%s as num?)?.toDouble()", expr)
	case "boolean":
		if required && !s.Nullable {
			return fmt.Sprintf("(%s as bool?) ?? false", expr)
		}
		return fmt.Sprintf("%s as bool?", expr)
	case "array":
		inner := dartDecode(s.Items, "e", true)
		list := fmt.Sprintf("(%s as List<dynamic>?)?.map((e) => %s).toList()", expr, inner)
		if required {
			return list + " ?? const []"
		}
		return list
	case "object":
		if s.AdditionalProperties != nil {
			t := dartType(s.AdditionalProperties)
			m := fmt.Sprintf("(%s as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as %s))", expr, t)
			if required {
				return m + " ?? const {}"
			}
			return m
		}
		if required {
			return fmt.Sprintf("(%s as Map<String, dynamic>?) ?? const {}", expr)
		}
		return fmt.Sprintf("%s as Map<String, dynamic>?", expr)
	}
	return expr
}

func dartEncode(s *Schema, field string, nullable bool) string {
	if s == nil {
		return field
	}
	access := "."
	if nullable {
		access = "?."
	}
	if s.Ref != "" {
		return field + access + "toJson()"
	}
	switch s.Type {
	case "string":
		if s.Format == "date-time" {
			return field + access + "toIso8601String()"
		}
	case "array":
		if s.Items != nil && s.Items.Ref != "" {
			return field + access + "map((e) => e.toJson()).toList()"
		}
	}
	return field
}

// Dart's reserved words. A field named `enum` or `default` compiles to garbage,
// so these get a suffix. Built-in identifiers that are legal as field names
// (async, await, required, …) are deliberately not listed.
var dartReserved = map[string]bool{
	"assert": true, "break": true, "case": true, "catch": true, "class": true,
	"const": true, "continue": true, "default": true, "do": true, "else": true,
	"enum": true, "extends": true, "false": true, "final": true, "finally": true,
	"for": true, "if": true, "in": true, "is": true, "new": true, "null": true,
	"rethrow": true, "return": true, "super": true, "switch": true, "this": true,
	"throw": true, "true": true, "try": true, "var": true, "void": true, "while": true,
	"with": true,
}

// dartField converts snake_case to lowerCamelCase.
func dartField(name string) string {
	parts := strings.Split(name, "_")
	out := parts[0]
	for _, p := range parts[1:] {
		if p == "" {
			continue
		}
		out += strings.ToUpper(p[:1]) + p[1:]
	}
	if dartReserved[out] {
		out += "Value"
	}
	return out
}
