package apispec

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// The generated files, keyed by path relative to the repository root.
const (
	FileOpenAPI = "docs/openapi.yaml"
	FileDart    = "mobile/lib/api/generated.dart"
	FileTS      = "frontend/types/api.generated.ts"
)

// Generate produces every artefact derived from the Go contract.
func Generate() (map[string][]byte, error) {
	reg, ops := Build()
	dart, err := emitDart(reg, ops)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		FileOpenAPI: emitOpenAPI(reg, ops),
		FileDart:    dart,
		FileTS:      emitTypeScript(reg),
	}, nil
}

const header = "# Generated by `make apigen` from the Go types in backend/internal.\n" +
	"# Do not edit by hand: change the Go structs and regenerate.\n"

func emitOpenAPI(reg *Registry, ops []Operation) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString(`openapi: 3.0.3
info:
  title: TikTok Carousel Studio API
  version: "1.0"
  description: |
    Session-cookie authenticated API. Every protected endpoint checks resource
    ownership, so a wrong id is a 404 rather than another user's data.
servers:
  - url: http://localhost:8080/api/v1
    description: local development
paths:
`)

	// Group operations by path so each path appears once.
	byPath := map[string][]Operation{}
	var paths []string
	for _, op := range ops {
		if _, seen := byPath[op.Path]; !seen {
			paths = append(paths, op.Path)
		}
		byPath[op.Path] = append(byPath[op.Path], op)
	}
	sort.Strings(paths)

	for _, path := range paths {
		fmt.Fprintf(&b, "  %s:\n", path)
		for _, param := range pathParams(path) {
			_ = param
		}
		if params := pathParams(path); len(params) > 0 {
			b.WriteString("    parameters:\n")
			for _, p := range params {
				fmt.Fprintf(&b, "      - name: %s\n        in: path\n        required: true\n        schema: {type: string}\n", p)
			}
		}
		for _, op := range byPath[path] {
			fmt.Fprintf(&b, "    %s:\n", strings.ToLower(op.Method))
			fmt.Fprintf(&b, "      operationId: %s\n", op.OperationID)
			fmt.Fprintf(&b, "      summary: %s\n", op.Summary)
			if len(op.Query) > 0 {
				b.WriteString("      parameters:\n")
				var names []string
				for name := range op.Query {
					names = append(names, name)
				}
				sort.Strings(names)
				for _, name := range names {
					fmt.Fprintf(&b, "        - name: %s\n          in: query\n          required: false\n          description: %s\n          schema: {type: string}\n",
						name, op.Query[name])
				}
			}
			if op.Body != nil {
				fmt.Fprintf(&b, "      requestBody:\n        required: true\n        content:\n          application/json:\n            schema:\n              $ref: '#/components/schemas/%s'\n",
					reg.TypeName(op.Body))
			}
			b.WriteString("      responses:\n")
			if op.Response == nil {
				b.WriteString("        '204': {description: No content}\n")
			} else {
				fmt.Fprintf(&b, "        '200':\n          description: OK\n          content:\n            application/json:\n              schema:\n                $ref: '#/components/schemas/%s'\n",
					reg.TypeName(op.Response))
			}
			b.WriteString("        '401': {$ref: '#/components/responses/Error'}\n")
			b.WriteString("        '404': {$ref: '#/components/responses/Error'}\n")
		}
	}

	b.WriteString("components:\n  responses:\n    Error:\n      description: Error\n      content:\n        application/json:\n          schema:\n            $ref: '#/components/schemas/ErrorResponse'\n  schemas:\n")
	reg.Register(errorResponseType())
	for _, name := range reg.Names() {
		fmt.Fprintf(&b, "    %s:\n", name)
		writeYAMLSchema(&b, reg.Schemas[name], 6)
	}
	return b.Bytes()
}

func writeYAMLSchema(b *bytes.Buffer, s *Schema, indent int) {
	pad := strings.Repeat(" ", indent)
	if s.Ref != "" {
		fmt.Fprintf(b, "%s$ref: '%s'\n", pad, s.Ref)
		return
	}
	if s.Type != "" {
		fmt.Fprintf(b, "%stype: %s\n", pad, s.Type)
	}
	if s.Format != "" {
		fmt.Fprintf(b, "%sformat: %s\n", pad, s.Format)
	}
	if s.Nullable {
		fmt.Fprintf(b, "%snullable: true\n", pad)
	}
	if s.Items != nil {
		fmt.Fprintf(b, "%sitems:\n", pad)
		writeYAMLSchema(b, s.Items, indent+2)
	}
	if s.AdditionalProperties != nil {
		fmt.Fprintf(b, "%sadditionalProperties:\n", pad)
		writeYAMLSchema(b, s.AdditionalProperties, indent+2)
	}
	if len(s.Required) > 0 {
		fmt.Fprintf(b, "%srequired: [%s]\n", pad, strings.Join(s.Required, ", "))
	}
	if len(s.Properties) > 0 {
		fmt.Fprintf(b, "%sproperties:\n", pad)
		var names []string
		for name := range s.Properties {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			fmt.Fprintf(b, "%s  %s:\n", pad, name)
			writeYAMLSchema(b, s.Properties[name], indent+4)
		}
	}
}

func pathParams(path string) []string {
	var out []string
	for _, part := range strings.Split(path, "/") {
		if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") {
			out = append(out, strings.Trim(part, "{}"))
		}
	}
	return out
}
