package apispec

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// emitTypeScript writes the web app's view of the same contract. The
// hand-written types in types/index.ts are asserted against these, so a
// backend change that the web app has not absorbed fails the type check.
func emitTypeScript(reg *Registry) []byte {
	var b bytes.Buffer
	b.WriteString("// Generated by `make apigen` from the Go types in backend/internal.\n")
	b.WriteString("// Do not edit by hand: change the Go structs and regenerate.\n\n")

	for _, name := range reg.Names() {
		s := reg.Schemas[name]
		required := map[string]bool{}
		for _, r := range s.Required {
			required[r] = true
		}
		var fields []string
		for f := range s.Properties {
			fields = append(fields, f)
		}
		sort.Strings(fields)

		fmt.Fprintf(&b, "export type %s = {\n", name)
		for _, f := range fields {
			optional := ""
			if !required[f] {
				optional = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", f, optional, tsType(s.Properties[f]))
		}
		b.WriteString("};\n\n")
	}
	return b.Bytes()
}

func tsType(s *Schema) string {
	if s == nil {
		return "unknown"
	}
	if s.Ref != "" {
		return strings.TrimPrefix(s.Ref, "#/components/schemas/")
	}
	base := "unknown"
	switch s.Type {
	case "string":
		base = "string"
	case "integer", "number":
		base = "number"
	case "boolean":
		base = "boolean"
	case "array":
		base = tsType(s.Items) + "[]"
	case "object":
		if s.AdditionalProperties != nil {
			base = "Record<string, " + tsType(s.AdditionalProperties) + ">"
		} else {
			base = "Record<string, unknown>"
		}
	}
	if s.Nullable {
		base += " | null"
	}
	return base
}
