// Generated by `make apigen` from the Go types in backend/internal.
// Do not edit by hand: change the Go structs and regenerate.

// ignore_for_file: unnecessary_this, prefer_final_locals

import 'dart:convert';

import 'package:http/http.dart' as http;

/// Thrown for any non-2xx response. The backend sends a stable `code`
/// plus a human message; the UI localises by code and falls back to the message.
class ApiException implements Exception {
  ApiException(this.statusCode, this.code, this.message);

  final int statusCode;
  final String code;
  final String message;

  @override
  String toString() => 'ApiException($statusCode, $code): $message';
}

class Asset {
  Asset({
    this.carouselId,
    required this.createdAt,
    required this.fileSize,
    required this.height,
    required this.id,
    this.metadata,
    required this.mimeType,
    this.projectId,
    required this.source,
    this.sourceId,
    this.url,
    required this.userId,
    required this.width,
  });

  factory Asset.fromJson(Map<String, dynamic> json) => Asset(
        carouselId: json['carousel_id'] as String?,
        createdAt: DateTime.parse(json['created_at'] as String),
        fileSize: (json['file_size'] as num?)?.toInt() ?? 0,
        height: (json['height'] as num?)?.toInt() ?? 0,
        id: (json['id'] as String?) ?? '',
        metadata: json['metadata'] as Map<String, dynamic>?,
        mimeType: (json['mime_type'] as String?) ?? '',
        projectId: json['project_id'] as String?,
        source: (json['source'] as String?) ?? '',
        sourceId: json['source_id'] as String?,
        url: json['url'] as String?,
        userId: (json['user_id'] as String?) ?? '',
        width: (json['width'] as num?)?.toInt() ?? 0,
      );

  final String? carouselId;
  final DateTime createdAt;
  final int fileSize;
  final int height;
  final String id;
  final Map<String, dynamic>? metadata;
  final String mimeType;
  final String? projectId;
  final String source;
  final String? sourceId;
  final String? url;
  final String userId;
  final int width;

  Asset copyWith({
    String? carouselId,
    DateTime? createdAt,
    int? fileSize,
    int? height,
    String? id,
    Map<String, dynamic>? metadata,
    String? mimeType,
    String? projectId,
    String? source,
    String? sourceId,
    String? url,
    String? userId,
    int? width,
  }) =>
      Asset(
        carouselId: carouselId ?? this.carouselId,
        createdAt: createdAt ?? this.createdAt,
        fileSize: fileSize ?? this.fileSize,
        height: height ?? this.height,
        id: id ?? this.id,
        metadata: metadata ?? this.metadata,
        mimeType: mimeType ?? this.mimeType,
        projectId: projectId ?? this.projectId,
        source: source ?? this.source,
        sourceId: sourceId ?? this.sourceId,
        url: url ?? this.url,
        userId: userId ?? this.userId,
        width: width ?? this.width,
      );

  Map<String, dynamic> toJson() => {
        'carousel_id': carouselId,
        'created_at': createdAt.toIso8601String(),
        'file_size': fileSize,
        'height': height,
        'id': id,
        'metadata': metadata,
        'mime_type': mimeType,
        'project_id': projectId,
        'source': source,
        'source_id': sourceId,
        'url': url,
        'user_id': userId,
        'width': width,
      };
}

class AuthConfigResponse {
  AuthConfigResponse({
    required this.devLoginEnabled,
    required this.googleEnabled,
  });

  factory AuthConfigResponse.fromJson(Map<String, dynamic> json) => AuthConfigResponse(
        devLoginEnabled: (json['dev_login_enabled'] as bool?) ?? false,
        googleEnabled: (json['google_enabled'] as bool?) ?? false,
      );

  final bool devLoginEnabled;
  final bool googleEnabled;

  AuthConfigResponse copyWith({
    bool? devLoginEnabled,
    bool? googleEnabled,
  }) =>
      AuthConfigResponse(
        devLoginEnabled: devLoginEnabled ?? this.devLoginEnabled,
        googleEnabled: googleEnabled ?? this.googleEnabled,
      );

  Map<String, dynamic> toJson() => {
        'dev_login_enabled': devLoginEnabled,
        'google_enabled': googleEnabled,
      };
}

class AuthUser {
  AuthUser({
    required this.avatarUrl,
    required this.createdAt,
    required this.email,
    required this.id,
    required this.name,
    required this.provider,
  });

  factory AuthUser.fromJson(Map<String, dynamic> json) => AuthUser(
        avatarUrl: (json['avatar_url'] as String?) ?? '',
        createdAt: DateTime.parse(json['created_at'] as String),
        email: (json['email'] as String?) ?? '',
        id: (json['id'] as String?) ?? '',
        name: (json['name'] as String?) ?? '',
        provider: (json['provider'] as String?) ?? '',
      );

  final String avatarUrl;
  final DateTime createdAt;
  final String email;
  final String id;
  final String name;
  final String provider;

  AuthUser copyWith({
    String? avatarUrl,
    DateTime? createdAt,
    String? email,
    String? id,
    String? name,
    String? provider,
  }) =>
      AuthUser(
        avatarUrl: avatarUrl ?? this.avatarUrl,
        createdAt: createdAt ?? this.createdAt,
        email: email ?? this.email,
        id: id ?? this.id,
        name: name ?? this.name,
        provider: provider ?? this.provider,
      );

  Map<String, dynamic> toJson() => {
        'avatar_url': avatarUrl,
        'created_at': createdAt.toIso8601String(),
        'email': email,
        'id': id,
        'name': name,
        'provider': provider,
      };
}

class Carousel {
  Carousel({
    required this.canvasHeight,
    required this.canvasRatio,
    required this.canvasWidth,
    required this.createdAt,
    required this.designVersion,
    required this.formulaId,
    required this.id,
    this.input,
    required this.platform,
    required this.projectId,
    required this.schemaVersion,
    required this.status,
    this.thumbnailUrl,
    required this.title,
    required this.updatedAt,
  });

  factory Carousel.fromJson(Map<String, dynamic> json) => Carousel(
        canvasHeight: (json['canvas_height'] as num?)?.toInt() ?? 0,
        canvasRatio: (json['canvas_ratio'] as String?) ?? '',
        canvasWidth: (json['canvas_width'] as num?)?.toInt() ?? 0,
        createdAt: DateTime.parse(json['created_at'] as String),
        designVersion: (json['design_version'] as num?)?.toInt() ?? 0,
        formulaId: (json['formula_id'] as String?) ?? '',
        id: (json['id'] as String?) ?? '',
        input: json['input'] as Map<String, dynamic>?,
        platform: (json['platform'] as String?) ?? '',
        projectId: (json['project_id'] as String?) ?? '',
        schemaVersion: (json['schema_version'] as num?)?.toInt() ?? 0,
        status: (json['status'] as String?) ?? '',
        thumbnailUrl: json['thumbnail_url'] as String?,
        title: (json['title'] as String?) ?? '',
        updatedAt: DateTime.parse(json['updated_at'] as String),
      );

  final int canvasHeight;
  final String canvasRatio;
  final int canvasWidth;
  final DateTime createdAt;
  final int designVersion;
  final String formulaId;
  final String id;
  final Map<String, dynamic>? input;
  final String platform;
  final String projectId;
  final int schemaVersion;
  final String status;
  final String? thumbnailUrl;
  final String title;
  final DateTime updatedAt;

  Carousel copyWith({
    int? canvasHeight,
    String? canvasRatio,
    int? canvasWidth,
    DateTime? createdAt,
    int? designVersion,
    String? formulaId,
    String? id,
    Map<String, dynamic>? input,
    String? platform,
    String? projectId,
    int? schemaVersion,
    String? status,
    String? thumbnailUrl,
    String? title,
    DateTime? updatedAt,
  }) =>
      Carousel(
        canvasHeight: canvasHeight ?? this.canvasHeight,
        canvasRatio: canvasRatio ?? this.canvasRatio,
        canvasWidth: canvasWidth ?? this.canvasWidth,
        createdAt: createdAt ?? this.createdAt,
        designVersion: designVersion ?? this.designVersion,
        formulaId: formulaId ?? this.formulaId,
        id: id ?? this.id,
        input: input ?? this.input,
        platform: platform ?? this.platform,
        projectId: projectId ?? this.projectId,
        schemaVersion: schemaVersion ?? this.schemaVersion,
        status: status ?? this.status,
        thumbnailUrl: thumbnailUrl ?? this.thumbnailUrl,
        title: title ?? this.title,
        updatedAt: updatedAt ?? this.updatedAt,
      );

  Map<String, dynamic> toJson() => {
        'canvas_height': canvasHeight,
        'canvas_ratio': canvasRatio,
        'canvas_width': canvasWidth,
        'created_at': createdAt.toIso8601String(),
        'design_version': designVersion,
        'formula_id': formulaId,
        'id': id,
        'input': input,
        'platform': platform,
        'project_id': projectId,
        'schema_version': schemaVersion,
        'status': status,
        'thumbnail_url': thumbnailUrl,
        'title': title,
        'updated_at': updatedAt.toIso8601String(),
      };
}

class CarouselCaption {
  CarouselCaption({
    required this.caption,
    required this.edited,
    this.generatedAt,
    required this.hashtags,
    required this.updatedAt,
  });

  factory CarouselCaption.fromJson(Map<String, dynamic> json) => CarouselCaption(
        caption: (json['caption'] as String?) ?? '',
        edited: (json['edited'] as bool?) ?? false,
        generatedAt: json['generated_at'] == null ? null : DateTime.tryParse(json['generated_at'] as String),
        hashtags: (json['hashtags'] as List<dynamic>?)?.map((e) => (e as String?) ?? '').toList() ?? const [],
        updatedAt: DateTime.parse(json['updated_at'] as String),
      );

  final String caption;
  final bool edited;
  final DateTime? generatedAt;
  final List<String> hashtags;
  final DateTime updatedAt;

  CarouselCaption copyWith({
    String? caption,
    bool? edited,
    DateTime? generatedAt,
    List<String>? hashtags,
    DateTime? updatedAt,
  }) =>
      CarouselCaption(
        caption: caption ?? this.caption,
        edited: edited ?? this.edited,
        generatedAt: generatedAt ?? this.generatedAt,
        hashtags: hashtags ?? this.hashtags,
        updatedAt: updatedAt ?? this.updatedAt,
      );

  Map<String, dynamic> toJson() => {
        'caption': caption,
        'edited': edited,
        'generated_at': generatedAt?.toIso8601String(),
        'hashtags': hashtags,
        'updated_at': updatedAt.toIso8601String(),
      };
}

class CarouselDesignView {
  CarouselDesignView({
    required this.design,
    required this.version,
  });

  factory CarouselDesignView.fromJson(Map<String, dynamic> json) => CarouselDesignView(
        design: Design.fromJson(json['design'] as Map<String, dynamic>),
        version: (json['version'] as num?)?.toInt() ?? 0,
      );

  final Design design;
  final int version;

  CarouselDesignView copyWith({
    Design? design,
    int? version,
  }) =>
      CarouselDesignView(
        design: design ?? this.design,
        version: version ?? this.version,
      );

  Map<String, dynamic> toJson() => {
        'design': design.toJson(),
        'version': version,
      };
}

class CarouselResponse {
  CarouselResponse({
    required this.carousel,
    this.job,
  });

  factory CarouselResponse.fromJson(Map<String, dynamic> json) => CarouselResponse(
        carousel: Carousel.fromJson(json['carousel'] as Map<String, dynamic>),
        job: json['job'] == null ? null : Job.fromJson(json['job'] as Map<String, dynamic>),
      );

  final Carousel carousel;
  final Job? job;

  CarouselResponse copyWith({
    Carousel? carousel,
    Job? job,
  }) =>
      CarouselResponse(
        carousel: carousel ?? this.carousel,
        job: job ?? this.job,
      );

  Map<String, dynamic> toJson() => {
        'carousel': carousel.toJson(),
        'job': job?.toJson(),
      };
}

class CarouselsResponse {
  CarouselsResponse({
    required this.carousels,
  });

  factory CarouselsResponse.fromJson(Map<String, dynamic> json) => CarouselsResponse(
        carousels: (json['carousels'] as List<dynamic>?)?.map((e) => Carousel.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
      );

  final List<Carousel> carousels;

  CarouselsResponse copyWith({
    List<Carousel>? carousels,
  }) =>
      CarouselsResponse(
        carousels: carousels ?? this.carousels,
      );

  Map<String, dynamic> toJson() => {
        'carousels': carousels.map((e) => e.toJson()).toList(),
      };
}

class ContentDocument {
  ContentDocument({
    required this.formulaId,
    required this.formulaReason,
    required this.schemaVersion,
    required this.slides,
    required this.title,
  });

  factory ContentDocument.fromJson(Map<String, dynamic> json) => ContentDocument(
        formulaId: (json['formula_id'] as String?) ?? '',
        formulaReason: (json['formula_reason'] as String?) ?? '',
        schemaVersion: (json['schema_version'] as String?) ?? '',
        slides: (json['slides'] as List<dynamic>?)?.map((e) => (e as Map<String, dynamic>?) ?? const {}).toList() ?? const [],
        title: (json['title'] as String?) ?? '',
      );

  final String formulaId;
  final String formulaReason;
  final String schemaVersion;
  final List<Map<String, dynamic>> slides;
  final String title;

  ContentDocument copyWith({
    String? formulaId,
    String? formulaReason,
    String? schemaVersion,
    List<Map<String, dynamic>>? slides,
    String? title,
  }) =>
      ContentDocument(
        formulaId: formulaId ?? this.formulaId,
        formulaReason: formulaReason ?? this.formulaReason,
        schemaVersion: schemaVersion ?? this.schemaVersion,
        slides: slides ?? this.slides,
        title: title ?? this.title,
      );

  Map<String, dynamic> toJson() => {
        'formula_id': formulaId,
        'formula_reason': formulaReason,
        'schema_version': schemaVersion,
        'slides': slides,
        'title': title,
      };
}

class CreateProjectRequest {
  CreateProjectRequest({
    required this.language,
    required this.niche,
  });

  factory CreateProjectRequest.fromJson(Map<String, dynamic> json) => CreateProjectRequest(
        language: (json['language'] as String?) ?? '',
        niche: (json['niche'] as String?) ?? '',
      );

  final String language;
  final String niche;

  CreateProjectRequest copyWith({
    String? language,
    String? niche,
  }) =>
      CreateProjectRequest(
        language: language ?? this.language,
        niche: niche ?? this.niche,
      );

  Map<String, dynamic> toJson() => {
        'language': language,
        'niche': niche,
      };
}

class Design {
  Design({
    required this.canvas,
    required this.palette,
    required this.slides,
    required this.version,
  });

  factory Design.fromJson(Map<String, dynamic> json) => Design(
        canvas: DesignCanvas.fromJson(json['canvas'] as Map<String, dynamic>),
        palette: DesignPalette.fromJson(json['palette'] as Map<String, dynamic>),
        slides: (json['slides'] as List<dynamic>?)?.map((e) => DesignSlide.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
        version: (json['version'] as String?) ?? '',
      );

  final DesignCanvas canvas;
  final DesignPalette palette;
  final List<DesignSlide> slides;
  final String version;

  Design copyWith({
    DesignCanvas? canvas,
    DesignPalette? palette,
    List<DesignSlide>? slides,
    String? version,
  }) =>
      Design(
        canvas: canvas ?? this.canvas,
        palette: palette ?? this.palette,
        slides: slides ?? this.slides,
        version: version ?? this.version,
      );

  Map<String, dynamic> toJson() => {
        'canvas': canvas.toJson(),
        'palette': palette.toJson(),
        'slides': slides.map((e) => e.toJson()).toList(),
        'version': version,
      };
}

class DesignCanvas {
  DesignCanvas({
    required this.height,
    required this.ratio,
    this.reservedBottom,
    this.reservedTop,
    required this.safeArea,
    required this.width,
  });

  factory DesignCanvas.fromJson(Map<String, dynamic> json) => DesignCanvas(
        height: (json['height'] as num?)?.toInt() ?? 0,
        ratio: (json['ratio'] as String?) ?? '',
        reservedBottom: (json['reserved_bottom'] as num?)?.toInt(),
        reservedTop: (json['reserved_top'] as num?)?.toInt(),
        safeArea: DesignSafeArea.fromJson(json['safe_area'] as Map<String, dynamic>),
        width: (json['width'] as num?)?.toInt() ?? 0,
      );

  final int height;
  final String ratio;
  final int? reservedBottom;
  final int? reservedTop;
  final DesignSafeArea safeArea;
  final int width;

  DesignCanvas copyWith({
    int? height,
    String? ratio,
    int? reservedBottom,
    int? reservedTop,
    DesignSafeArea? safeArea,
    int? width,
  }) =>
      DesignCanvas(
        height: height ?? this.height,
        ratio: ratio ?? this.ratio,
        reservedBottom: reservedBottom ?? this.reservedBottom,
        reservedTop: reservedTop ?? this.reservedTop,
        safeArea: safeArea ?? this.safeArea,
        width: width ?? this.width,
      );

  Map<String, dynamic> toJson() => {
        'height': height,
        'ratio': ratio,
        'reserved_bottom': reservedBottom,
        'reserved_top': reservedTop,
        'safe_area': safeArea.toJson(),
        'width': width,
      };
}

class DesignElement {
  DesignElement({
    this.assetId,
    this.content,
    this.fill,
    this.fit,
    required this.height,
    required this.id,
    this.locked,
    required this.opacity,
    this.overlay,
    this.radius,
    this.role,
    this.shape,
    this.style,
    required this.type,
    this.url,
    required this.width,
    required this.x,
    required this.y,
    required this.z,
  });

  factory DesignElement.fromJson(Map<String, dynamic> json) => DesignElement(
        assetId: json['asset_id'] as String?,
        content: json['content'] as String?,
        fill: json['fill'] as String?,
        fit: json['fit'] as String?,
        height: (json['height'] as num?)?.toDouble() ?? 0,
        id: (json['id'] as String?) ?? '',
        locked: json['locked'] as bool?,
        opacity: (json['opacity'] as num?)?.toDouble() ?? 0,
        overlay: json['overlay'] == null ? null : DesignOverlay.fromJson(json['overlay'] as Map<String, dynamic>),
        radius: (json['radius'] as num?)?.toDouble(),
        role: json['role'] as String?,
        shape: json['shape'] as String?,
        style: json['style'] == null ? null : DesignStyle.fromJson(json['style'] as Map<String, dynamic>),
        type: (json['type'] as String?) ?? '',
        url: json['url'] as String?,
        width: (json['width'] as num?)?.toDouble() ?? 0,
        x: (json['x'] as num?)?.toDouble() ?? 0,
        y: (json['y'] as num?)?.toDouble() ?? 0,
        z: (json['z'] as num?)?.toInt() ?? 0,
      );

  final String? assetId;
  final String? content;
  final String? fill;
  final String? fit;
  final double height;
  final String id;
  final bool? locked;
  final double opacity;
  final DesignOverlay? overlay;
  final double? radius;
  final String? role;
  final String? shape;
  final DesignStyle? style;
  final String type;
  final String? url;
  final double width;
  final double x;
  final double y;
  final int z;

  DesignElement copyWith({
    String? assetId,
    String? content,
    String? fill,
    String? fit,
    double? height,
    String? id,
    bool? locked,
    double? opacity,
    DesignOverlay? overlay,
    double? radius,
    String? role,
    String? shape,
    DesignStyle? style,
    String? type,
    String? url,
    double? width,
    double? x,
    double? y,
    int? z,
  }) =>
      DesignElement(
        assetId: assetId ?? this.assetId,
        content: content ?? this.content,
        fill: fill ?? this.fill,
        fit: fit ?? this.fit,
        height: height ?? this.height,
        id: id ?? this.id,
        locked: locked ?? this.locked,
        opacity: opacity ?? this.opacity,
        overlay: overlay ?? this.overlay,
        radius: radius ?? this.radius,
        role: role ?? this.role,
        shape: shape ?? this.shape,
        style: style ?? this.style,
        type: type ?? this.type,
        url: url ?? this.url,
        width: width ?? this.width,
        x: x ?? this.x,
        y: y ?? this.y,
        z: z ?? this.z,
      );

  Map<String, dynamic> toJson() => {
        'asset_id': assetId,
        'content': content,
        'fill': fill,
        'fit': fit,
        'height': height,
        'id': id,
        'locked': locked,
        'opacity': opacity,
        'overlay': overlay?.toJson(),
        'radius': radius,
        'role': role,
        'shape': shape,
        'style': style?.toJson(),
        'type': type,
        'url': url,
        'width': width,
        'x': x,
        'y': y,
        'z': z,
      };
}

class DesignOverlay {
  DesignOverlay({
    required this.color,
    required this.opacity,
  });

  factory DesignOverlay.fromJson(Map<String, dynamic> json) => DesignOverlay(
        color: (json['color'] as String?) ?? '',
        opacity: (json['opacity'] as num?)?.toDouble() ?? 0,
      );

  final String color;
  final double opacity;

  DesignOverlay copyWith({
    String? color,
    double? opacity,
  }) =>
      DesignOverlay(
        color: color ?? this.color,
        opacity: opacity ?? this.opacity,
      );

  Map<String, dynamic> toJson() => {
        'color': color,
        'opacity': opacity,
      };
}

class DesignPalette {
  DesignPalette({
    required this.accent,
    required this.background,
    required this.primary,
    required this.secondary,
    required this.text,
  });

  factory DesignPalette.fromJson(Map<String, dynamic> json) => DesignPalette(
        accent: (json['accent'] as String?) ?? '',
        background: (json['background'] as String?) ?? '',
        primary: (json['primary'] as String?) ?? '',
        secondary: (json['secondary'] as String?) ?? '',
        text: (json['text'] as String?) ?? '',
      );

  final String accent;
  final String background;
  final String primary;
  final String secondary;
  final String text;

  DesignPalette copyWith({
    String? accent,
    String? background,
    String? primary,
    String? secondary,
    String? text,
  }) =>
      DesignPalette(
        accent: accent ?? this.accent,
        background: background ?? this.background,
        primary: primary ?? this.primary,
        secondary: secondary ?? this.secondary,
        text: text ?? this.text,
      );

  Map<String, dynamic> toJson() => {
        'accent': accent,
        'background': background,
        'primary': primary,
        'secondary': secondary,
        'text': text,
      };
}

class DesignPreset {
  DesignPreset({
    required this.height,
    required this.label,
    required this.ratio,
    required this.width,
  });

  factory DesignPreset.fromJson(Map<String, dynamic> json) => DesignPreset(
        height: (json['height'] as num?)?.toInt() ?? 0,
        label: (json['label'] as String?) ?? '',
        ratio: (json['ratio'] as String?) ?? '',
        width: (json['width'] as num?)?.toInt() ?? 0,
      );

  final int height;
  final String label;
  final String ratio;
  final int width;

  DesignPreset copyWith({
    int? height,
    String? label,
    String? ratio,
    int? width,
  }) =>
      DesignPreset(
        height: height ?? this.height,
        label: label ?? this.label,
        ratio: ratio ?? this.ratio,
        width: width ?? this.width,
      );

  Map<String, dynamic> toJson() => {
        'height': height,
        'label': label,
        'ratio': ratio,
        'width': width,
      };
}

class DesignSafeArea {
  DesignSafeArea({
    required this.height,
    required this.width,
    required this.x,
    required this.y,
  });

  factory DesignSafeArea.fromJson(Map<String, dynamic> json) => DesignSafeArea(
        height: (json['height'] as num?)?.toInt() ?? 0,
        width: (json['width'] as num?)?.toInt() ?? 0,
        x: (json['x'] as num?)?.toInt() ?? 0,
        y: (json['y'] as num?)?.toInt() ?? 0,
      );

  final int height;
  final int width;
  final int x;
  final int y;

  DesignSafeArea copyWith({
    int? height,
    int? width,
    int? x,
    int? y,
  }) =>
      DesignSafeArea(
        height: height ?? this.height,
        width: width ?? this.width,
        x: x ?? this.x,
        y: y ?? this.y,
      );

  Map<String, dynamic> toJson() => {
        'height': height,
        'width': width,
        'x': x,
        'y': y,
      };
}

class DesignSlide {
  DesignSlide({
    required this.background,
    required this.elements,
    required this.id,
    this.imageIntent,
    this.imageQuery,
    required this.index,
    required this.role,
    this.template,
  });

  factory DesignSlide.fromJson(Map<String, dynamic> json) => DesignSlide(
        background: (json['background'] as String?) ?? '',
        elements: (json['elements'] as List<dynamic>?)?.map((e) => DesignElement.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
        id: (json['id'] as String?) ?? '',
        imageIntent: json['image_intent'] as String?,
        imageQuery: json['image_query'] as String?,
        index: (json['index'] as num?)?.toInt() ?? 0,
        role: (json['role'] as String?) ?? '',
        template: json['template'] as String?,
      );

  final String background;
  final List<DesignElement> elements;
  final String id;
  final String? imageIntent;
  final String? imageQuery;
  final int index;
  final String role;
  final String? template;

  DesignSlide copyWith({
    String? background,
    List<DesignElement>? elements,
    String? id,
    String? imageIntent,
    String? imageQuery,
    int? index,
    String? role,
    String? template,
  }) =>
      DesignSlide(
        background: background ?? this.background,
        elements: elements ?? this.elements,
        id: id ?? this.id,
        imageIntent: imageIntent ?? this.imageIntent,
        imageQuery: imageQuery ?? this.imageQuery,
        index: index ?? this.index,
        role: role ?? this.role,
        template: template ?? this.template,
      );

  Map<String, dynamic> toJson() => {
        'background': background,
        'elements': elements.map((e) => e.toJson()).toList(),
        'id': id,
        'image_intent': imageIntent,
        'image_query': imageQuery,
        'index': index,
        'role': role,
        'template': template,
      };
}

class DesignStyle {
  DesignStyle({
    required this.color,
    required this.fontFamily,
    required this.fontSize,
    required this.fontWeight,
    required this.lineHeight,
    required this.textAlign,
  });

  factory DesignStyle.fromJson(Map<String, dynamic> json) => DesignStyle(
        color: (json['color'] as String?) ?? '',
        fontFamily: (json['fontFamily'] as String?) ?? '',
        fontSize: (json['fontSize'] as num?)?.toDouble() ?? 0,
        fontWeight: (json['fontWeight'] as num?)?.toInt() ?? 0,
        lineHeight: (json['lineHeight'] as num?)?.toDouble() ?? 0,
        textAlign: (json['textAlign'] as String?) ?? '',
      );

  final String color;
  final String fontFamily;
  final double fontSize;
  final int fontWeight;
  final double lineHeight;
  final String textAlign;

  DesignStyle copyWith({
    String? color,
    String? fontFamily,
    double? fontSize,
    int? fontWeight,
    double? lineHeight,
    String? textAlign,
  }) =>
      DesignStyle(
        color: color ?? this.color,
        fontFamily: fontFamily ?? this.fontFamily,
        fontSize: fontSize ?? this.fontSize,
        fontWeight: fontWeight ?? this.fontWeight,
        lineHeight: lineHeight ?? this.lineHeight,
        textAlign: textAlign ?? this.textAlign,
      );

  Map<String, dynamic> toJson() => {
        'color': color,
        'fontFamily': fontFamily,
        'fontSize': fontSize,
        'fontWeight': fontWeight,
        'lineHeight': lineHeight,
        'textAlign': textAlign,
      };
}

class DevLoginRequest {
  DevLoginRequest({
    required this.email,
    this.name,
  });

  factory DevLoginRequest.fromJson(Map<String, dynamic> json) => DevLoginRequest(
        email: (json['email'] as String?) ?? '',
        name: json['name'] as String?,
      );

  final String email;
  final String? name;

  DevLoginRequest copyWith({
    String? email,
    String? name,
  }) =>
      DevLoginRequest(
        email: email ?? this.email,
        name: name ?? this.name,
      );

  Map<String, dynamic> toJson() => {
        'email': email,
        'name': name,
      };
}

class ExportJob {
  ExportJob({
    required this.carouselId,
    this.completedAt,
    required this.createdAt,
    this.downloadUrl,
    this.error,
    required this.format,
    required this.id,
    required this.progress,
    required this.status,
  });

  factory ExportJob.fromJson(Map<String, dynamic> json) => ExportJob(
        carouselId: (json['carousel_id'] as String?) ?? '',
        completedAt: json['completed_at'] == null ? null : DateTime.tryParse(json['completed_at'] as String),
        createdAt: DateTime.parse(json['created_at'] as String),
        downloadUrl: json['download_url'] as String?,
        error: json['error'] as String?,
        format: (json['format'] as String?) ?? '',
        id: (json['id'] as String?) ?? '',
        progress: (json['progress'] as num?)?.toInt() ?? 0,
        status: (json['status'] as String?) ?? '',
      );

  final String carouselId;
  final DateTime? completedAt;
  final DateTime createdAt;
  final String? downloadUrl;
  final String? error;
  final String format;
  final String id;
  final int progress;
  final String status;

  ExportJob copyWith({
    String? carouselId,
    DateTime? completedAt,
    DateTime? createdAt,
    String? downloadUrl,
    String? error,
    String? format,
    String? id,
    int? progress,
    String? status,
  }) =>
      ExportJob(
        carouselId: carouselId ?? this.carouselId,
        completedAt: completedAt ?? this.completedAt,
        createdAt: createdAt ?? this.createdAt,
        downloadUrl: downloadUrl ?? this.downloadUrl,
        error: error ?? this.error,
        format: format ?? this.format,
        id: id ?? this.id,
        progress: progress ?? this.progress,
        status: status ?? this.status,
      );

  Map<String, dynamic> toJson() => {
        'carousel_id': carouselId,
        'completed_at': completedAt?.toIso8601String(),
        'created_at': createdAt.toIso8601String(),
        'download_url': downloadUrl,
        'error': error,
        'format': format,
        'id': id,
        'progress': progress,
        'status': status,
      };
}

class GenerateCarouselRequest {
  GenerateCarouselRequest({
    required this.inputs,
    required this.ratio,
  });

  factory GenerateCarouselRequest.fromJson(Map<String, dynamic> json) => GenerateCarouselRequest(
        inputs: (json['inputs'] as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as dynamic)) ?? const {},
        ratio: (json['ratio'] as String?) ?? '',
      );

  final Map<String, dynamic> inputs;
  final String ratio;

  GenerateCarouselRequest copyWith({
    Map<String, dynamic>? inputs,
    String? ratio,
  }) =>
      GenerateCarouselRequest(
        inputs: inputs ?? this.inputs,
        ratio: ratio ?? this.ratio,
      );

  Map<String, dynamic> toJson() => {
        'inputs': inputs,
        'ratio': ratio,
      };
}

class GenerateCarouselResponse {
  GenerateCarouselResponse({
    required this.carousel,
    required this.carouselId,
    required this.jobId,
    required this.status,
  });

  factory GenerateCarouselResponse.fromJson(Map<String, dynamic> json) => GenerateCarouselResponse(
        carousel: Carousel.fromJson(json['carousel'] as Map<String, dynamic>),
        carouselId: (json['carousel_id'] as String?) ?? '',
        jobId: (json['job_id'] as String?) ?? '',
        status: (json['status'] as String?) ?? '',
      );

  final Carousel carousel;
  final String carouselId;
  final String jobId;
  final String status;

  GenerateCarouselResponse copyWith({
    Carousel? carousel,
    String? carouselId,
    String? jobId,
    String? status,
  }) =>
      GenerateCarouselResponse(
        carousel: carousel ?? this.carousel,
        carouselId: carouselId ?? this.carouselId,
        jobId: jobId ?? this.jobId,
        status: status ?? this.status,
      );

  Map<String, dynamic> toJson() => {
        'carousel': carousel.toJson(),
        'carousel_id': carouselId,
        'job_id': jobId,
        'status': status,
      };
}

class ImageCandidatesResponse {
  ImageCandidatesResponse({
    required this.candidates,
    this.page,
    required this.query,
  });

  factory ImageCandidatesResponse.fromJson(Map<String, dynamic> json) => ImageCandidatesResponse(
        candidates: (json['candidates'] as List<dynamic>?)?.map((e) => ImagePublicCandidate.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
        page: (json['page'] as num?)?.toInt(),
        query: (json['query'] as String?) ?? '',
      );

  final List<ImagePublicCandidate> candidates;
  final int? page;
  final String query;

  ImageCandidatesResponse copyWith({
    List<ImagePublicCandidate>? candidates,
    int? page,
    String? query,
  }) =>
      ImageCandidatesResponse(
        candidates: candidates ?? this.candidates,
        page: page ?? this.page,
        query: query ?? this.query,
      );

  Map<String, dynamic> toJson() => {
        'candidates': candidates.map((e) => e.toJson()).toList(),
        'page': page,
        'query': query,
      };
}

class ImagePublicCandidate {
  ImagePublicCandidate({
    this.color,
    this.description,
    required this.height,
    required this.id,
    this.photographerName,
    this.photographerUrl,
    required this.previewUrl,
    required this.provider,
    this.sourceUrl,
    required this.thumbUrl,
    required this.width,
  });

  factory ImagePublicCandidate.fromJson(Map<String, dynamic> json) => ImagePublicCandidate(
        color: json['color'] as String?,
        description: json['description'] as String?,
        height: (json['height'] as num?)?.toInt() ?? 0,
        id: (json['id'] as String?) ?? '',
        photographerName: json['photographer_name'] as String?,
        photographerUrl: json['photographer_url'] as String?,
        previewUrl: (json['preview_url'] as String?) ?? '',
        provider: (json['provider'] as String?) ?? '',
        sourceUrl: json['source_url'] as String?,
        thumbUrl: (json['thumb_url'] as String?) ?? '',
        width: (json['width'] as num?)?.toInt() ?? 0,
      );

  final String? color;
  final String? description;
  final int height;
  final String id;
  final String? photographerName;
  final String? photographerUrl;
  final String previewUrl;
  final String provider;
  final String? sourceUrl;
  final String thumbUrl;
  final int width;

  ImagePublicCandidate copyWith({
    String? color,
    String? description,
    int? height,
    String? id,
    String? photographerName,
    String? photographerUrl,
    String? previewUrl,
    String? provider,
    String? sourceUrl,
    String? thumbUrl,
    int? width,
  }) =>
      ImagePublicCandidate(
        color: color ?? this.color,
        description: description ?? this.description,
        height: height ?? this.height,
        id: id ?? this.id,
        photographerName: photographerName ?? this.photographerName,
        photographerUrl: photographerUrl ?? this.photographerUrl,
        previewUrl: previewUrl ?? this.previewUrl,
        provider: provider ?? this.provider,
        sourceUrl: sourceUrl ?? this.sourceUrl,
        thumbUrl: thumbUrl ?? this.thumbUrl,
        width: width ?? this.width,
      );

  Map<String, dynamic> toJson() => {
        'color': color,
        'description': description,
        'height': height,
        'id': id,
        'photographer_name': photographerName,
        'photographer_url': photographerUrl,
        'preview_url': previewUrl,
        'provider': provider,
        'source_url': sourceUrl,
        'thumb_url': thumbUrl,
        'width': width,
      };
}

class Job {
  Job({
    required this.attempt,
    required this.carouselId,
    this.completedAt,
    required this.createdAt,
    required this.currentStep,
    this.errorCode,
    this.errorMessage,
    required this.id,
    required this.lastCompletedStep,
    required this.progress,
    required this.projectId,
    required this.status,
    required this.type,
    required this.userId,
  });

  factory Job.fromJson(Map<String, dynamic> json) => Job(
        attempt: (json['attempt'] as num?)?.toInt() ?? 0,
        carouselId: (json['carousel_id'] as String?) ?? '',
        completedAt: json['completed_at'] == null ? null : DateTime.tryParse(json['completed_at'] as String),
        createdAt: DateTime.parse(json['created_at'] as String),
        currentStep: (json['current_step'] as String?) ?? '',
        errorCode: json['error_code'] as String?,
        errorMessage: json['error_message'] as String?,
        id: (json['id'] as String?) ?? '',
        lastCompletedStep: (json['last_completed_step'] as String?) ?? '',
        progress: (json['progress'] as num?)?.toInt() ?? 0,
        projectId: (json['project_id'] as String?) ?? '',
        status: (json['status'] as String?) ?? '',
        type: (json['type'] as String?) ?? '',
        userId: (json['user_id'] as String?) ?? '',
      );

  final int attempt;
  final String carouselId;
  final DateTime? completedAt;
  final DateTime createdAt;
  final String currentStep;
  final String? errorCode;
  final String? errorMessage;
  final String id;
  final String lastCompletedStep;
  final int progress;
  final String projectId;
  final String status;
  final String type;
  final String userId;

  Job copyWith({
    int? attempt,
    String? carouselId,
    DateTime? completedAt,
    DateTime? createdAt,
    String? currentStep,
    String? errorCode,
    String? errorMessage,
    String? id,
    String? lastCompletedStep,
    int? progress,
    String? projectId,
    String? status,
    String? type,
    String? userId,
  }) =>
      Job(
        attempt: attempt ?? this.attempt,
        carouselId: carouselId ?? this.carouselId,
        completedAt: completedAt ?? this.completedAt,
        createdAt: createdAt ?? this.createdAt,
        currentStep: currentStep ?? this.currentStep,
        errorCode: errorCode ?? this.errorCode,
        errorMessage: errorMessage ?? this.errorMessage,
        id: id ?? this.id,
        lastCompletedStep: lastCompletedStep ?? this.lastCompletedStep,
        progress: progress ?? this.progress,
        projectId: projectId ?? this.projectId,
        status: status ?? this.status,
        type: type ?? this.type,
        userId: userId ?? this.userId,
      );

  Map<String, dynamic> toJson() => {
        'attempt': attempt,
        'carousel_id': carouselId,
        'completed_at': completedAt?.toIso8601String(),
        'created_at': createdAt.toIso8601String(),
        'current_step': currentStep,
        'error_code': errorCode,
        'error_message': errorMessage,
        'id': id,
        'last_completed_step': lastCompletedStep,
        'progress': progress,
        'project_id': projectId,
        'status': status,
        'type': type,
        'user_id': userId,
      };
}

class JobResponse {
  JobResponse({
    required this.carouselId,
    required this.currentStep,
    this.errorMessage,
    required this.id,
    required this.progress,
    required this.status,
    required this.steps,
  });

  factory JobResponse.fromJson(Map<String, dynamic> json) => JobResponse(
        carouselId: (json['carousel_id'] as String?) ?? '',
        currentStep: (json['current_step'] as String?) ?? '',
        errorMessage: json['error_message'] as String?,
        id: (json['id'] as String?) ?? '',
        progress: (json['progress'] as num?)?.toInt() ?? 0,
        status: (json['status'] as String?) ?? '',
        steps: (json['steps'] as List<dynamic>?)?.map((e) => (e as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as dynamic)) ?? const {}).toList() ?? const [],
      );

  final String carouselId;
  final String currentStep;
  final String? errorMessage;
  final String id;
  final int progress;
  final String status;
  final List<Map<String, dynamic>> steps;

  JobResponse copyWith({
    String? carouselId,
    String? currentStep,
    String? errorMessage,
    String? id,
    int? progress,
    String? status,
    List<Map<String, dynamic>>? steps,
  }) =>
      JobResponse(
        carouselId: carouselId ?? this.carouselId,
        currentStep: currentStep ?? this.currentStep,
        errorMessage: errorMessage ?? this.errorMessage,
        id: id ?? this.id,
        progress: progress ?? this.progress,
        status: status ?? this.status,
        steps: steps ?? this.steps,
      );

  Map<String, dynamic> toJson() => {
        'carousel_id': carouselId,
        'current_step': currentStep,
        'error_message': errorMessage,
        'id': id,
        'progress': progress,
        'status': status,
        'steps': steps,
      };
}

class Language {
  Language({
    required this.code,
    required this.englishName,
    required this.nativeName,
  });

  factory Language.fromJson(Map<String, dynamic> json) => Language(
        code: (json['code'] as String?) ?? '',
        englishName: (json['english_name'] as String?) ?? '',
        nativeName: (json['native_name'] as String?) ?? '',
      );

  final String code;
  final String englishName;
  final String nativeName;

  Language copyWith({
    String? code,
    String? englishName,
    String? nativeName,
  }) =>
      Language(
        code: code ?? this.code,
        englishName: englishName ?? this.englishName,
        nativeName: nativeName ?? this.nativeName,
      );

  Map<String, dynamic> toJson() => {
        'code': code,
        'english_name': englishName,
        'native_name': nativeName,
      };
}

class Project {
  Project({
    required this.brand,
    required this.carouselCount,
    this.context,
    required this.contextVersion,
    required this.createdAt,
    required this.description,
    required this.id,
    required this.language,
    required this.name,
    required this.niche,
    required this.status,
    required this.updatedAt,
    required this.userId,
  });

  factory Project.fromJson(Map<String, dynamic> json) => Project(
        brand: ProjectBrand.fromJson(json['brand'] as Map<String, dynamic>),
        carouselCount: (json['carousel_count'] as num?)?.toInt() ?? 0,
        context: json['context'] as Map<String, dynamic>?,
        contextVersion: (json['context_version'] as num?)?.toInt() ?? 0,
        createdAt: DateTime.parse(json['created_at'] as String),
        description: (json['description'] as String?) ?? '',
        id: (json['id'] as String?) ?? '',
        language: (json['language'] as String?) ?? '',
        name: (json['name'] as String?) ?? '',
        niche: (json['niche'] as String?) ?? '',
        status: (json['status'] as String?) ?? '',
        updatedAt: DateTime.parse(json['updated_at'] as String),
        userId: (json['user_id'] as String?) ?? '',
      );

  final ProjectBrand brand;
  final int carouselCount;
  final Map<String, dynamic>? context;
  final int contextVersion;
  final DateTime createdAt;
  final String description;
  final String id;
  final String language;
  final String name;
  final String niche;
  final String status;
  final DateTime updatedAt;
  final String userId;

  Project copyWith({
    ProjectBrand? brand,
    int? carouselCount,
    Map<String, dynamic>? context,
    int? contextVersion,
    DateTime? createdAt,
    String? description,
    String? id,
    String? language,
    String? name,
    String? niche,
    String? status,
    DateTime? updatedAt,
    String? userId,
  }) =>
      Project(
        brand: brand ?? this.brand,
        carouselCount: carouselCount ?? this.carouselCount,
        context: context ?? this.context,
        contextVersion: contextVersion ?? this.contextVersion,
        createdAt: createdAt ?? this.createdAt,
        description: description ?? this.description,
        id: id ?? this.id,
        language: language ?? this.language,
        name: name ?? this.name,
        niche: niche ?? this.niche,
        status: status ?? this.status,
        updatedAt: updatedAt ?? this.updatedAt,
        userId: userId ?? this.userId,
      );

  Map<String, dynamic> toJson() => {
        'brand': brand.toJson(),
        'carousel_count': carouselCount,
        'context': context,
        'context_version': contextVersion,
        'created_at': createdAt.toIso8601String(),
        'description': description,
        'id': id,
        'language': language,
        'name': name,
        'niche': niche,
        'status': status,
        'updated_at': updatedAt.toIso8601String(),
        'user_id': userId,
      };
}

class ProjectAudience {
  ProjectAudience({
    required this.demographics,
    required this.description,
    required this.painPoints,
  });

  factory ProjectAudience.fromJson(Map<String, dynamic> json) => ProjectAudience(
        demographics: (json['demographics'] as String?) ?? '',
        description: (json['description'] as String?) ?? '',
        painPoints: (json['pain_points'] as List<dynamic>?)?.map((e) => (e as String?) ?? '').toList() ?? const [],
      );

  final String demographics;
  final String description;
  final List<String> painPoints;

  ProjectAudience copyWith({
    String? demographics,
    String? description,
    List<String>? painPoints,
  }) =>
      ProjectAudience(
        demographics: demographics ?? this.demographics,
        description: description ?? this.description,
        painPoints: painPoints ?? this.painPoints,
      );

  Map<String, dynamic> toJson() => {
        'demographics': demographics,
        'description': description,
        'pain_points': painPoints,
      };
}

class ProjectBrand {
  ProjectBrand({
    this.accentColor,
    required this.display,
    this.fontFamily,
    this.handle,
    this.logoAssetId,
    this.logoUrl,
    this.primaryColor,
    this.secondaryColor,
    this.website,
  });

  factory ProjectBrand.fromJson(Map<String, dynamic> json) => ProjectBrand(
        accentColor: json['accent_color'] as String?,
        display: ProjectBrandDisplay.fromJson(json['display'] as Map<String, dynamic>),
        fontFamily: json['font_family'] as String?,
        handle: json['handle'] as String?,
        logoAssetId: json['logo_asset_id'] as String?,
        logoUrl: json['logo_url'] as String?,
        primaryColor: json['primary_color'] as String?,
        secondaryColor: json['secondary_color'] as String?,
        website: json['website'] as String?,
      );

  final String? accentColor;
  final ProjectBrandDisplay display;
  final String? fontFamily;
  final String? handle;
  final String? logoAssetId;
  final String? logoUrl;
  final String? primaryColor;
  final String? secondaryColor;
  final String? website;

  ProjectBrand copyWith({
    String? accentColor,
    ProjectBrandDisplay? display,
    String? fontFamily,
    String? handle,
    String? logoAssetId,
    String? logoUrl,
    String? primaryColor,
    String? secondaryColor,
    String? website,
  }) =>
      ProjectBrand(
        accentColor: accentColor ?? this.accentColor,
        display: display ?? this.display,
        fontFamily: fontFamily ?? this.fontFamily,
        handle: handle ?? this.handle,
        logoAssetId: logoAssetId ?? this.logoAssetId,
        logoUrl: logoUrl ?? this.logoUrl,
        primaryColor: primaryColor ?? this.primaryColor,
        secondaryColor: secondaryColor ?? this.secondaryColor,
        website: website ?? this.website,
      );

  Map<String, dynamic> toJson() => {
        'accent_color': accentColor,
        'display': display.toJson(),
        'font_family': fontFamily,
        'handle': handle,
        'logo_asset_id': logoAssetId,
        'logo_url': logoUrl,
        'primary_color': primaryColor,
        'secondary_color': secondaryColor,
        'website': website,
      };
}

class ProjectBrandDisplay {
  ProjectBrandDisplay({
    required this.handle,
    required this.logo,
    required this.website,
  });

  factory ProjectBrandDisplay.fromJson(Map<String, dynamic> json) => ProjectBrandDisplay(
        handle: ProjectPlacement.fromJson(json['handle'] as Map<String, dynamic>),
        logo: ProjectPlacement.fromJson(json['logo'] as Map<String, dynamic>),
        website: ProjectPlacement.fromJson(json['website'] as Map<String, dynamic>),
      );

  final ProjectPlacement handle;
  final ProjectPlacement logo;
  final ProjectPlacement website;

  ProjectBrandDisplay copyWith({
    ProjectPlacement? handle,
    ProjectPlacement? logo,
    ProjectPlacement? website,
  }) =>
      ProjectBrandDisplay(
        handle: handle ?? this.handle,
        logo: logo ?? this.logo,
        website: website ?? this.website,
      );

  Map<String, dynamic> toJson() => {
        'handle': handle.toJson(),
        'logo': logo.toJson(),
        'website': website.toJson(),
      };
}

class ProjectCTA {
  ProjectCTA({
    required this.id,
    required this.label,
  });

  factory ProjectCTA.fromJson(Map<String, dynamic> json) => ProjectCTA(
        id: (json['id'] as String?) ?? '',
        label: (json['label'] as String?) ?? '',
      );

  final String id;
  final String label;

  ProjectCTA copyWith({
    String? id,
    String? label,
  }) =>
      ProjectCTA(
        id: id ?? this.id,
        label: label ?? this.label,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'label': label,
      };
}

class ProjectContext {
  ProjectContext({
    required this.audience,
    required this.contentPillars,
    required this.ctaOptions,
    required this.preferredAngles,
    required this.schemaVersion,
    required this.suggestedTopics,
    required this.tone,
    required this.writingStyle,
  });

  factory ProjectContext.fromJson(Map<String, dynamic> json) => ProjectContext(
        audience: ProjectAudience.fromJson(json['audience'] as Map<String, dynamic>),
        contentPillars: (json['content_pillars'] as List<dynamic>?)?.map((e) => ProjectPillar.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
        ctaOptions: (json['cta_options'] as List<dynamic>?)?.map((e) => ProjectCTA.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
        preferredAngles: (json['preferred_angles'] as List<dynamic>?)?.map((e) => (e as String?) ?? '').toList() ?? const [],
        schemaVersion: (json['schema_version'] as String?) ?? '',
        suggestedTopics: (json['suggested_topics'] as List<dynamic>?)?.map((e) => (e as String?) ?? '').toList() ?? const [],
        tone: (json['tone'] as List<dynamic>?)?.map((e) => (e as String?) ?? '').toList() ?? const [],
        writingStyle: (json['writing_style'] as String?) ?? '',
      );

  final ProjectAudience audience;
  final List<ProjectPillar> contentPillars;
  final List<ProjectCTA> ctaOptions;
  final List<String> preferredAngles;
  final String schemaVersion;
  final List<String> suggestedTopics;
  final List<String> tone;
  final String writingStyle;

  ProjectContext copyWith({
    ProjectAudience? audience,
    List<ProjectPillar>? contentPillars,
    List<ProjectCTA>? ctaOptions,
    List<String>? preferredAngles,
    String? schemaVersion,
    List<String>? suggestedTopics,
    List<String>? tone,
    String? writingStyle,
  }) =>
      ProjectContext(
        audience: audience ?? this.audience,
        contentPillars: contentPillars ?? this.contentPillars,
        ctaOptions: ctaOptions ?? this.ctaOptions,
        preferredAngles: preferredAngles ?? this.preferredAngles,
        schemaVersion: schemaVersion ?? this.schemaVersion,
        suggestedTopics: suggestedTopics ?? this.suggestedTopics,
        tone: tone ?? this.tone,
        writingStyle: writingStyle ?? this.writingStyle,
      );

  Map<String, dynamic> toJson() => {
        'audience': audience.toJson(),
        'content_pillars': contentPillars.map((e) => e.toJson()).toList(),
        'cta_options': ctaOptions.map((e) => e.toJson()).toList(),
        'preferred_angles': preferredAngles,
        'schema_version': schemaVersion,
        'suggested_topics': suggestedTopics,
        'tone': tone,
        'writing_style': writingStyle,
      };
}

class ProjectPillar {
  ProjectPillar({
    required this.description,
    required this.id,
    required this.name,
  });

  factory ProjectPillar.fromJson(Map<String, dynamic> json) => ProjectPillar(
        description: (json['description'] as String?) ?? '',
        id: (json['id'] as String?) ?? '',
        name: (json['name'] as String?) ?? '',
      );

  final String description;
  final String id;
  final String name;

  ProjectPillar copyWith({
    String? description,
    String? id,
    String? name,
  }) =>
      ProjectPillar(
        description: description ?? this.description,
        id: id ?? this.id,
        name: name ?? this.name,
      );

  Map<String, dynamic> toJson() => {
        'description': description,
        'id': id,
        'name': name,
      };
}

class ProjectPlacement {
  ProjectPlacement({
    required this.position,
    required this.scope,
  });

  factory ProjectPlacement.fromJson(Map<String, dynamic> json) => ProjectPlacement(
        position: (json['position'] as String?) ?? '',
        scope: (json['scope'] as String?) ?? '',
      );

  final String position;
  final String scope;

  ProjectPlacement copyWith({
    String? position,
    String? scope,
  }) =>
      ProjectPlacement(
        position: position ?? this.position,
        scope: scope ?? this.scope,
      );

  Map<String, dynamic> toJson() => {
        'position': position,
        'scope': scope,
      };
}

class ProjectSource {
  ProjectSource({
    required this.domain,
    required this.sourceType,
    required this.title,
    required this.url,
  });

  factory ProjectSource.fromJson(Map<String, dynamic> json) => ProjectSource(
        domain: (json['domain'] as String?) ?? '',
        sourceType: (json['source_type'] as String?) ?? '',
        title: (json['title'] as String?) ?? '',
        url: (json['url'] as String?) ?? '',
      );

  final String domain;
  final String sourceType;
  final String title;
  final String url;

  ProjectSource copyWith({
    String? domain,
    String? sourceType,
    String? title,
    String? url,
  }) =>
      ProjectSource(
        domain: domain ?? this.domain,
        sourceType: sourceType ?? this.sourceType,
        title: title ?? this.title,
        url: url ?? this.url,
      );

  Map<String, dynamic> toJson() => {
        'domain': domain,
        'source_type': sourceType,
        'title': title,
        'url': url,
      };
}

class ProjectsResponse {
  ProjectsResponse({
    required this.projects,
  });

  factory ProjectsResponse.fromJson(Map<String, dynamic> json) => ProjectsResponse(
        projects: (json['projects'] as List<dynamic>?)?.map((e) => Project.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
      );

  final List<Project> projects;

  ProjectsResponse copyWith({
    List<Project>? projects,
  }) =>
      ProjectsResponse(
        projects: projects ?? this.projects,
      );

  Map<String, dynamic> toJson() => {
        'projects': projects.map((e) => e.toJson()).toList(),
      };
}

class RegistryFont {
  RegistryFont({
    required this.cssStack,
    required this.family,
    required this.id,
    required this.vietnamese,
    required this.weights,
  });

  factory RegistryFont.fromJson(Map<String, dynamic> json) => RegistryFont(
        cssStack: (json['css_stack'] as String?) ?? '',
        family: (json['family'] as String?) ?? '',
        id: (json['id'] as String?) ?? '',
        vietnamese: (json['vietnamese'] as bool?) ?? false,
        weights: (json['weights'] as List<dynamic>?)?.map((e) => (e as num?)?.toInt() ?? 0).toList() ?? const [],
      );

  final String cssStack;
  final String family;
  final String id;
  final bool vietnamese;
  final List<int> weights;

  RegistryFont copyWith({
    String? cssStack,
    String? family,
    String? id,
    bool? vietnamese,
    List<int>? weights,
  }) =>
      RegistryFont(
        cssStack: cssStack ?? this.cssStack,
        family: family ?? this.family,
        id: id ?? this.id,
        vietnamese: vietnamese ?? this.vietnamese,
        weights: weights ?? this.weights,
      );

  Map<String, dynamic> toJson() => {
        'css_stack': cssStack,
        'family': family,
        'id': id,
        'vietnamese': vietnamese,
        'weights': weights,
      };
}

class RegistryFormula {
  RegistryFormula({
    required this.description,
    required this.id,
    required this.name,
    required this.recommendedFor,
    required this.structure,
  });

  factory RegistryFormula.fromJson(Map<String, dynamic> json) => RegistryFormula(
        description: (json['description'] as String?) ?? '',
        id: (json['id'] as String?) ?? '',
        name: (json['name'] as String?) ?? '',
        recommendedFor: (json['recommended_for'] as String?) ?? '',
        structure: (json['structure'] as List<dynamic>?)?.map((e) => (e as String?) ?? '').toList() ?? const [],
      );

  final String description;
  final String id;
  final String name;
  final String recommendedFor;
  final List<String> structure;

  RegistryFormula copyWith({
    String? description,
    String? id,
    String? name,
    String? recommendedFor,
    List<String>? structure,
  }) =>
      RegistryFormula(
        description: description ?? this.description,
        id: id ?? this.id,
        name: name ?? this.name,
        recommendedFor: recommendedFor ?? this.recommendedFor,
        structure: structure ?? this.structure,
      );

  Map<String, dynamic> toJson() => {
        'description': description,
        'id': id,
        'name': name,
        'recommended_for': recommendedFor,
        'structure': structure,
      };
}

class RegistryResponse {
  RegistryResponse({
    required this.fonts,
    required this.formulas,
    required this.languages,
    required this.presets,
  });

  factory RegistryResponse.fromJson(Map<String, dynamic> json) => RegistryResponse(
        fonts: (json['fonts'] as List<dynamic>?)?.map((e) => RegistryFont.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
        formulas: (json['formulas'] as List<dynamic>?)?.map((e) => RegistryFormula.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
        languages: (json['languages'] as List<dynamic>?)?.map((e) => Language.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
        presets: (json['presets'] as List<dynamic>?)?.map((e) => DesignPreset.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
      );

  final List<RegistryFont> fonts;
  final List<RegistryFormula> formulas;
  final List<Language> languages;
  final List<DesignPreset> presets;

  RegistryResponse copyWith({
    List<RegistryFont>? fonts,
    List<RegistryFormula>? formulas,
    List<Language>? languages,
    List<DesignPreset>? presets,
  }) =>
      RegistryResponse(
        fonts: fonts ?? this.fonts,
        formulas: formulas ?? this.formulas,
        languages: languages ?? this.languages,
        presets: presets ?? this.presets,
      );

  Map<String, dynamic> toJson() => {
        'fonts': fonts.map((e) => e.toJson()).toList(),
        'formulas': formulas.map((e) => e.toJson()).toList(),
        'languages': languages.map((e) => e.toJson()).toList(),
        'presets': presets.map((e) => e.toJson()).toList(),
      };
}

class SaveDesignRequest {
  SaveDesignRequest({
    required this.design,
    required this.version,
  });

  factory SaveDesignRequest.fromJson(Map<String, dynamic> json) => SaveDesignRequest(
        design: Design.fromJson(json['design'] as Map<String, dynamic>),
        version: (json['version'] as num?)?.toInt() ?? 0,
      );

  final Design design;
  final int version;

  SaveDesignRequest copyWith({
    Design? design,
    int? version,
  }) =>
      SaveDesignRequest(
        design: design ?? this.design,
        version: version ?? this.version,
      );

  Map<String, dynamic> toJson() => {
        'design': design.toJson(),
        'version': version,
      };
}

class SchemaForm {
  SchemaForm({
    required this.properties,
    required this.version,
  });

  factory SchemaForm.fromJson(Map<String, dynamic> json) => SchemaForm(
        properties: (json['properties'] as List<dynamic>?)?.map((e) => SchemaProperty.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
        version: (json['version'] as num?)?.toInt() ?? 0,
      );

  final List<SchemaProperty> properties;
  final int version;

  SchemaForm copyWith({
    List<SchemaProperty>? properties,
    int? version,
  }) =>
      SchemaForm(
        properties: properties ?? this.properties,
        version: version ?? this.version,
      );

  Map<String, dynamic> toJson() => {
        'properties': properties.map((e) => e.toJson()).toList(),
        'version': version,
      };
}

class SchemaProperty {
  SchemaProperty({
    required this.component,
    this.defaultValue,
    this.description,
    this.enumValue,
    this.enumLabels,
    this.help,
    this.items,
    this.maxLength,
    this.maximum,
    this.minimum,
    required this.name,
    this.placeholder,
    required this.required,
    required this.title,
    required this.type,
  });

  factory SchemaProperty.fromJson(Map<String, dynamic> json) => SchemaProperty(
        component: (json['component'] as String?) ?? '',
        defaultValue: json['default'],
        description: json['description'] as String?,
        enumValue: (json['enum'] as List<dynamic>?)?.map((e) => (e as String?) ?? '').toList(),
        enumLabels: (json['enum_labels'] as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as String)),
        help: json['help'] as String?,
        items: json['items'] as String?,
        maxLength: (json['max_length'] as num?)?.toInt(),
        maximum: (json['maximum'] as num?)?.toDouble(),
        minimum: (json['minimum'] as num?)?.toDouble(),
        name: (json['name'] as String?) ?? '',
        placeholder: json['placeholder'] as String?,
        required: (json['required'] as bool?) ?? false,
        title: (json['title'] as String?) ?? '',
        type: (json['type'] as String?) ?? '',
      );

  final String component;
  final dynamic defaultValue;
  final String? description;
  final List<String>? enumValue;
  final Map<String, String>? enumLabels;
  final String? help;
  final String? items;
  final int? maxLength;
  final double? maximum;
  final double? minimum;
  final String name;
  final String? placeholder;
  final bool required;
  final String title;
  final String type;

  SchemaProperty copyWith({
    String? component,
    dynamic defaultValue,
    String? description,
    List<String>? enumValue,
    Map<String, String>? enumLabels,
    String? help,
    String? items,
    int? maxLength,
    double? maximum,
    double? minimum,
    String? name,
    String? placeholder,
    bool? required,
    String? title,
    String? type,
  }) =>
      SchemaProperty(
        component: component ?? this.component,
        defaultValue: defaultValue ?? this.defaultValue,
        description: description ?? this.description,
        enumValue: enumValue ?? this.enumValue,
        enumLabels: enumLabels ?? this.enumLabels,
        help: help ?? this.help,
        items: items ?? this.items,
        maxLength: maxLength ?? this.maxLength,
        maximum: maximum ?? this.maximum,
        minimum: minimum ?? this.minimum,
        name: name ?? this.name,
        placeholder: placeholder ?? this.placeholder,
        required: required ?? this.required,
        title: title ?? this.title,
        type: type ?? this.type,
      );

  Map<String, dynamic> toJson() => {
        'component': component,
        'default': defaultValue,
        'description': description,
        'enum': enumValue,
        'enum_labels': enumLabels,
        'help': help,
        'items': items,
        'max_length': maxLength,
        'maximum': maximum,
        'minimum': minimum,
        'name': name,
        'placeholder': placeholder,
        'required': required,
        'title': title,
        'type': type,
      };
}

class SchemaResponse {
  SchemaResponse({
    required this.form,
    required this.version,
  });

  factory SchemaResponse.fromJson(Map<String, dynamic> json) => SchemaResponse(
        form: SchemaForm.fromJson(json['form'] as Map<String, dynamic>),
        version: (json['version'] as num?)?.toInt() ?? 0,
      );

  final SchemaForm form;
  final int version;

  SchemaResponse copyWith({
    SchemaForm? form,
    int? version,
  }) =>
      SchemaResponse(
        form: form ?? this.form,
        version: version ?? this.version,
      );

  Map<String, dynamic> toJson() => {
        'form': form.toJson(),
        'version': version,
      };
}

class SearchImagesRequest {
  SearchImagesRequest({
    this.page,
    this.query,
  });

  factory SearchImagesRequest.fromJson(Map<String, dynamic> json) => SearchImagesRequest(
        page: (json['page'] as num?)?.toInt(),
        query: json['query'] as String?,
      );

  final int? page;
  final String? query;

  SearchImagesRequest copyWith({
    int? page,
    String? query,
  }) =>
      SearchImagesRequest(
        page: page ?? this.page,
        query: query ?? this.query,
      );

  Map<String, dynamic> toJson() => {
        'page': page,
        'query': query,
      };
}

class SelectImageRequest {
  SelectImageRequest({
    required this.candidateId,
    required this.version,
  });

  factory SelectImageRequest.fromJson(Map<String, dynamic> json) => SelectImageRequest(
        candidateId: (json['candidate_id'] as String?) ?? '',
        version: (json['version'] as num?)?.toInt() ?? 0,
      );

  final String candidateId;
  final int version;

  SelectImageRequest copyWith({
    String? candidateId,
    int? version,
  }) =>
      SelectImageRequest(
        candidateId: candidateId ?? this.candidateId,
        version: version ?? this.version,
      );

  Map<String, dynamic> toJson() => {
        'candidate_id': candidateId,
        'version': version,
      };
}

class SelectImageResponse {
  SelectImageResponse({
    required this.asset,
    required this.version,
  });

  factory SelectImageResponse.fromJson(Map<String, dynamic> json) => SelectImageResponse(
        asset: Asset.fromJson(json['asset'] as Map<String, dynamic>),
        version: (json['version'] as num?)?.toInt() ?? 0,
      );

  final Asset asset;
  final int version;

  SelectImageResponse copyWith({
    Asset? asset,
    int? version,
  }) =>
      SelectImageResponse(
        asset: asset ?? this.asset,
        version: version ?? this.version,
      );

  Map<String, dynamic> toJson() => {
        'asset': asset.toJson(),
        'version': version,
      };
}

class SourcesResponse {
  SourcesResponse({
    required this.sources,
  });

  factory SourcesResponse.fromJson(Map<String, dynamic> json) => SourcesResponse(
        sources: (json['sources'] as List<dynamic>?)?.map((e) => ProjectSource.fromJson(e as Map<String, dynamic>)).toList() ?? const [],
      );

  final List<ProjectSource> sources;

  SourcesResponse copyWith({
    List<ProjectSource>? sources,
  }) =>
      SourcesResponse(
        sources: sources ?? this.sources,
      );

  Map<String, dynamic> toJson() => {
        'sources': sources.map((e) => e.toJson()).toList(),
      };
}

class UpdateCaptionRequest {
  UpdateCaptionRequest({
    required this.caption,
    required this.hashtags,
  });

  factory UpdateCaptionRequest.fromJson(Map<String, dynamic> json) => UpdateCaptionRequest(
        caption: (json['caption'] as String?) ?? '',
        hashtags: (json['hashtags'] as List<dynamic>?)?.map((e) => (e as String?) ?? '').toList() ?? const [],
      );

  final String caption;
  final List<String> hashtags;

  UpdateCaptionRequest copyWith({
    String? caption,
    List<String>? hashtags,
  }) =>
      UpdateCaptionRequest(
        caption: caption ?? this.caption,
        hashtags: hashtags ?? this.hashtags,
      );

  Map<String, dynamic> toJson() => {
        'caption': caption,
        'hashtags': hashtags,
      };
}

class UpdateCarouselRequest {
  UpdateCarouselRequest({
    this.status,
    this.title,
  });

  factory UpdateCarouselRequest.fromJson(Map<String, dynamic> json) => UpdateCarouselRequest(
        status: json['status'] as String?,
        title: json['title'] as String?,
      );

  final String? status;
  final String? title;

  UpdateCarouselRequest copyWith({
    String? status,
    String? title,
  }) =>
      UpdateCarouselRequest(
        status: status ?? this.status,
        title: title ?? this.title,
      );

  Map<String, dynamic> toJson() => {
        'status': status,
        'title': title,
      };
}

class UpdateProjectRequest {
  UpdateProjectRequest({
    this.brand,
    this.context,
    this.description,
    this.language,
    this.name,
    this.niche,
  });

  factory UpdateProjectRequest.fromJson(Map<String, dynamic> json) => UpdateProjectRequest(
        brand: json['brand'] == null ? null : ProjectBrand.fromJson(json['brand'] as Map<String, dynamic>),
        context: json['context'] == null ? null : ProjectContext.fromJson(json['context'] as Map<String, dynamic>),
        description: json['description'] as String?,
        language: json['language'] as String?,
        name: json['name'] as String?,
        niche: json['niche'] as String?,
      );

  final ProjectBrand? brand;
  final ProjectContext? context;
  final String? description;
  final String? language;
  final String? name;
  final String? niche;

  UpdateProjectRequest copyWith({
    ProjectBrand? brand,
    ProjectContext? context,
    String? description,
    String? language,
    String? name,
    String? niche,
  }) =>
      UpdateProjectRequest(
        brand: brand ?? this.brand,
        context: context ?? this.context,
        description: description ?? this.description,
        language: language ?? this.language,
        name: name ?? this.name,
        niche: niche ?? this.niche,
      );

  Map<String, dynamic> toJson() => {
        'brand': brand?.toJson(),
        'context': context?.toJson(),
        'description': description,
        'language': language,
        'name': name,
        'niche': niche,
      };
}

/// Typed client for the Carousel Studio API.
///
/// Authentication is a session cookie. Dart's http package does not keep a
/// cookie jar, so the session is captured from Set-Cookie on sign-in and sent
/// back on every later call — see [ApiClient.session].
class ApiClient {
  ApiClient({required this.baseUrl, http.Client? httpClient})
      : _http = httpClient ?? http.Client();

  final String baseUrl;
  final http.Client _http;

  /// The session cookie value, persisted by the caller across launches.
  String? session;

  Uri _uri(String path, [Map<String, String>? query]) {
    final cleaned = <String, String>{
      for (final entry in (query ?? {}).entries)
        if (entry.value.isNotEmpty) entry.key: entry.value,
    };
    return Uri.parse('$baseUrl/api/v1$path')
        .replace(queryParameters: cleaned.isEmpty ? null : cleaned);
  }

  Map<String, String> _headers({bool json = false}) {
    final headers = <String, String>{};
    if (json) headers['Content-Type'] = 'application/json';
    final cookie = session;
    if (cookie != null) headers['Cookie'] = cookie;
    return headers;
  }

  void _captureSession(http.Response res) {
    final raw = res.headers['set-cookie'];
    if (raw == null) return;
    final match = RegExp(r'tks_session=([^;]*)').firstMatch(raw);
    if (match == null) return;
    final value = match.group(1) ?? '';
    session = value.isEmpty ? null : 'tks_session=$value';
  }

  Future<dynamic> _send(String method, String path,
      {Object? body, Map<String, String>? query}) async {
    final request = http.Request(method, _uri(path, query))
      ..headers.addAll(_headers(json: body != null));
    if (body != null) request.body = jsonEncode(body);

    final res = await http.Response.fromStream(await _http.send(request));
    _captureSession(res);

    if (res.statusCode == 204 || res.body.isEmpty) {
      if (res.statusCode >= 300) {
        throw ApiException(res.statusCode, 'unknown', '');
      }
      return null;
    }
    final decoded = jsonDecode(utf8.decode(res.bodyBytes));
    if (res.statusCode >= 300) {
      final error = (decoded is Map<String, dynamic> ? decoded['error'] : null);
      throw ApiException(
        res.statusCode,
        (error is Map ? error['code'] as String? : null) ?? 'unknown',
        (error is Map ? error['message'] as String? : null) ?? '',
      );
    }
    return decoded;
  }

  /// Re-stamp the project brand kit
  Future<CarouselDesignView> applyBrand(String carouselId) async {
    final data = await _send('POST', '/carousels/$carouselId/apply-brand');
    return CarouselDesignView.fromJson(data as Map<String, dynamic>);
  }

  /// Archive a carousel
  Future<Carousel> archiveCarousel(String carouselId) async {
    final data = await _send('POST', '/carousels/$carouselId/archive');
    return Carousel.fromJson(data as Map<String, dynamic>);
  }

  /// Queue a PNG/ZIP export
  Future<ExportJob> createExport(String carouselId) async {
    final data = await _send('POST', '/carousels/$carouselId/export');
    return ExportJob.fromJson(data as Map<String, dynamic>);
  }

  /// Create a project from a niche description
  Future<Project> createProject(CreateProjectRequest body) async {
    final data = await _send('POST', '/projects', body: body.toJson());
    return Project.fromJson(data as Map<String, dynamic>);
  }

  /// Delete an asset
  Future<void> deleteAsset(String assetId) async {
    await _send('DELETE', '/assets/$assetId');
  }

  /// Soft-delete a carousel
  Future<void> deleteCarousel(String carouselId) async {
    await _send('DELETE', '/carousels/$carouselId');
  }

  /// Soft-delete a project
  Future<void> deleteProject(String projectId) async {
    await _send('DELETE', '/projects/$projectId');
  }

  /// Sign in with an email address (development only)
  Future<AuthUser> devLogin(DevLoginRequest body) async {
    final data = await _send('POST', '/auth/dev-login', body: body.toJson());
    return AuthUser.fromJson(data as Map<String, dynamic>);
  }

  /// Copy a carousel
  Future<Carousel> duplicateCarousel(String carouselId) async {
    final data = await _send('POST', '/carousels/$carouselId/duplicate');
    return Carousel.fromJson(data as Map<String, dynamic>);
  }

  /// Queue a carousel generation
  Future<GenerateCarouselResponse> generateCarousel(String projectId, GenerateCarouselRequest body) async {
    final data = await _send('POST', '/projects/$projectId/carousels/generate', body: body.toJson());
    return GenerateCarouselResponse.fromJson(data as Map<String, dynamic>);
  }

  /// One asset
  Future<Asset> getAsset(String assetId) async {
    final data = await _send('GET', '/assets/$assetId');
    return Asset.fromJson(data as Map<String, dynamic>);
  }

  /// Which sign-in methods are enabled
  Future<AuthConfigResponse> getAuthConfig() async {
    final data = await _send('GET', '/auth/config');
    return AuthConfigResponse.fromJson(data as Map<String, dynamic>);
  }

  /// Post caption and hashtags
  Future<CarouselCaption> getCaption(String carouselId) async {
    final data = await _send('GET', '/carousels/$carouselId/caption');
    return CarouselCaption.fromJson(data as Map<String, dynamic>);
  }

  /// One carousel and its latest job
  Future<CarouselResponse> getCarousel(String carouselId) async {
    final data = await _send('GET', '/carousels/$carouselId');
    return CarouselResponse.fromJson(data as Map<String, dynamic>);
  }

  /// The generated copy
  Future<ContentDocument> getCarouselContent(String carouselId) async {
    final data = await _send('GET', '/carousels/$carouselId/content');
    return ContentDocument.fromJson(data as Map<String, dynamic>);
  }

  /// The AI-generated input form
  Future<SchemaResponse> getCarouselForm(String projectId) async {
    final data = await _send('GET', '/projects/$projectId/schema');
    return SchemaResponse.fromJson(data as Map<String, dynamic>);
  }

  /// The signed-in user
  Future<AuthUser> getCurrentUser() async {
    final data = await _send('GET', '/auth/me');
    return AuthUser.fromJson(data as Map<String, dynamic>);
  }

  /// The current Design JSON
  Future<CarouselDesignView> getDesign(String carouselId) async {
    final data = await _send('GET', '/carousels/$carouselId/design');
    return CarouselDesignView.fromJson(data as Map<String, dynamic>);
  }

  /// Export progress and download URL
  Future<ExportJob> getExport(String exportId) async {
    final data = await _send('GET', '/exports/$exportId');
    return ExportJob.fromJson(data as Map<String, dynamic>);
  }

  /// Generation job progress
  Future<JobResponse> getJob(String jobId) async {
    final data = await _send('GET', '/jobs/$jobId');
    return JobResponse.fromJson(data as Map<String, dynamic>);
  }

  /// One project
  Future<Project> getProject(String projectId) async {
    final data = await _send('GET', '/projects/$projectId');
    return Project.fromJson(data as Map<String, dynamic>);
  }

  /// Fonts, formulas, canvas presets and content languages
  Future<RegistryResponse> getRegistry() async {
    final data = await _send('GET', '/registry');
    return RegistryResponse.fromJson(data as Map<String, dynamic>);
  }

  /// Sources cited during research
  Future<SourcesResponse> getResearchSources(String carouselId) async {
    final data = await _send('GET', '/carousels/$carouselId/sources');
    return SourcesResponse.fromJson(data as Map<String, dynamic>);
  }

  /// Image candidates for a slide
  Future<ImageCandidatesResponse> getSlideImages(String carouselId, String slideId) async {
    final data = await _send('GET', '/carousels/$carouselId/slides/$slideId/images');
    return ImageCandidatesResponse.fromJson(data as Map<String, dynamic>);
  }

  /// Carousels in a project
  Future<CarouselsResponse> listCarousels(String projectId, {String q = '', String status = ''}) async {
    final data = await _send('GET', '/projects/$projectId/carousels', query: {'q': q, 'status': status});
    return CarouselsResponse.fromJson(data as Map<String, dynamic>);
  }

  /// Every project the user owns
  Future<ProjectsResponse> listProjects() async {
    final data = await _send('GET', '/projects');
    return ProjectsResponse.fromJson(data as Map<String, dynamic>);
  }

  /// End the session
  Future<void> logout() async {
    await _send('POST', '/auth/logout');
  }

  /// Rewrite the caption with AI
  Future<CarouselCaption> regenerateCaption(String carouselId) async {
    final data = await _send('POST', '/carousels/$carouselId/caption/generate');
    return CarouselCaption.fromJson(data as Map<String, dynamic>);
  }

  /// Run generation again with the stored inputs
  Future<GenerateCarouselResponse> regenerateCarousel(String carouselId) async {
    final data = await _send('POST', '/carousels/$carouselId/regenerate');
    return GenerateCarouselResponse.fromJson(data as Map<String, dynamic>);
  }

  /// Rebuild the input form
  Future<SchemaResponse> regenerateCarouselForm(String projectId) async {
    final data = await _send('POST', '/projects/$projectId/generate-schema');
    return SchemaResponse.fromJson(data as Map<String, dynamic>);
  }

  /// Autosave with optimistic concurrency
  Future<CarouselDesignView> saveDesign(String carouselId, SaveDesignRequest body) async {
    final data = await _send('PATCH', '/carousels/$carouselId/design', body: body.toJson());
    return CarouselDesignView.fromJson(data as Map<String, dynamic>);
  }

  /// Search again, optionally with a new keyword
  Future<ImageCandidatesResponse> searchSlideImages(String carouselId, String slideId, SearchImagesRequest body) async {
    final data = await _send('POST', '/carousels/$carouselId/slides/$slideId/images/search', body: body.toJson());
    return ImageCandidatesResponse.fromJson(data as Map<String, dynamic>);
  }

  /// Use a candidate as the slide background
  Future<SelectImageResponse> selectSlideImage(String carouselId, String slideId, SelectImageRequest body) async {
    final data = await _send('POST', '/carousels/$carouselId/slides/$slideId/images/select', body: body.toJson());
    return SelectImageResponse.fromJson(data as Map<String, dynamic>);
  }

  /// Edit the caption
  Future<CarouselCaption> updateCaption(String carouselId, UpdateCaptionRequest body) async {
    final data = await _send('PATCH', '/carousels/$carouselId/caption', body: body.toJson());
    return CarouselCaption.fromJson(data as Map<String, dynamic>);
  }

  /// Rename or change status
  Future<Carousel> updateCarousel(String carouselId, UpdateCarouselRequest body) async {
    final data = await _send('PATCH', '/carousels/$carouselId', body: body.toJson());
    return Carousel.fromJson(data as Map<String, dynamic>);
  }

  /// Update identity, brand kit or AI strategy
  Future<Project> updateProject(String projectId, UpdateProjectRequest body) async {
    final data = await _send('PATCH', '/projects/$projectId', body: body.toJson());
    return Project.fromJson(data as Map<String, dynamic>);
  }

  void close() => _http.close();
}
