'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';

import { api } from './client';

export function useMe() {
  return useQuery({ queryKey: ['me'], queryFn: api.me, retry: false });
}

/** Redirects to /login when there is no session, so pages can assume a user. */
export function useRequireAuth() {
  const router = useRouter();
  const query = useMe();
  if (query.isError) {
    if (typeof window !== 'undefined') router.replace('/login');
  }
  return query;
}

export function useProjects() {
  return useQuery({ queryKey: ['projects'], queryFn: api.listProjects });
}

export function useProject(id: string) {
  return useQuery({ queryKey: ['project', id], queryFn: () => api.getProject(id), enabled: Boolean(id) });
}

export function useSchema(projectId: string) {
  return useQuery({
    queryKey: ['schema', projectId],
    queryFn: () => api.getSchema(projectId),
    enabled: Boolean(projectId),
    // The form is generated by AI on first request and can take a few seconds.
    retry: 2,
  });
}

export function useCarousels(projectId: string, filters: { status?: string; q?: string }) {
  return useQuery({
    queryKey: ['carousels', projectId, filters.status ?? 'all', filters.q ?? ''],
    queryFn: () => api.listCarousels(projectId, filters),
    enabled: Boolean(projectId),
  });
}

/** Polls a running job (§13: poll for MVP, SSE later). */
export function useJob(jobId: string | null) {
  return useQuery({
    queryKey: ['job', jobId],
    queryFn: () => api.getJob(jobId!),
    enabled: Boolean(jobId),
    refetchInterval: (query) => {
      const status = query.state.data?.status;
      return status === 'completed' || status === 'failed' ? false : 1500;
    },
  });
}

export function useDesign(carouselId: string) {
  return useQuery({
    queryKey: ['design', carouselId],
    queryFn: () => api.getDesign(carouselId),
    enabled: Boolean(carouselId),
    retry: false,
  });
}

/** Content languages the backend can actually render and export. */
export function useContentLanguages() {
  return useQuery({
    queryKey: ['registry'],
    queryFn: api.registry,
    staleTime: 60 * 60 * 1000,
    select: (r) => r.languages,
  });
}

export function useLogout() {
  const router = useRouter();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: api.logout,
    onSuccess: () => {
      qc.clear();
      router.replace('/login');
    },
  });
}
